// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XS_COMPUTE_ACOUSTICS_H
#define XS_COMPUTE_ACOUSTICS_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xs_compute_acoustics_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XS_compute_acoustics_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XS_compute_acoustics;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XS_compute_acoustics_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XS_compute_acoustics_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XS_compute_acoustics_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XS_compute_acoustics_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XS_compute_acoustics_Initialize(XS_compute_acoustics *InstancePtr, u16 DeviceId);
XS_compute_acoustics_Config* XS_compute_acoustics_LookupConfig(u16 DeviceId);
int XS_compute_acoustics_CfgInitialize(XS_compute_acoustics *InstancePtr, XS_compute_acoustics_Config *ConfigPtr);
#else
int XS_compute_acoustics_Initialize(XS_compute_acoustics *InstancePtr, const char* InstanceName);
int XS_compute_acoustics_Release(XS_compute_acoustics *InstancePtr);
#endif

void XS_compute_acoustics_Start(XS_compute_acoustics *InstancePtr);
u32 XS_compute_acoustics_IsDone(XS_compute_acoustics *InstancePtr);
u32 XS_compute_acoustics_IsIdle(XS_compute_acoustics *InstancePtr);
u32 XS_compute_acoustics_IsReady(XS_compute_acoustics *InstancePtr);
void XS_compute_acoustics_EnableAutoRestart(XS_compute_acoustics *InstancePtr);
void XS_compute_acoustics_DisableAutoRestart(XS_compute_acoustics *InstancePtr);


void XS_compute_acoustics_InterruptGlobalEnable(XS_compute_acoustics *InstancePtr);
void XS_compute_acoustics_InterruptGlobalDisable(XS_compute_acoustics *InstancePtr);
void XS_compute_acoustics_InterruptEnable(XS_compute_acoustics *InstancePtr, u32 Mask);
void XS_compute_acoustics_InterruptDisable(XS_compute_acoustics *InstancePtr, u32 Mask);
void XS_compute_acoustics_InterruptClear(XS_compute_acoustics *InstancePtr, u32 Mask);
u32 XS_compute_acoustics_InterruptGetEnabled(XS_compute_acoustics *InstancePtr);
u32 XS_compute_acoustics_InterruptGetStatus(XS_compute_acoustics *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
