// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xs_compute_acoustics.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XS_compute_acoustics_CfgInitialize(XS_compute_acoustics *InstancePtr, XS_compute_acoustics_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XS_compute_acoustics_Start(XS_compute_acoustics *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XS_compute_acoustics_ReadReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XS_compute_acoustics_WriteReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XS_compute_acoustics_IsDone(XS_compute_acoustics *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XS_compute_acoustics_ReadReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XS_compute_acoustics_IsIdle(XS_compute_acoustics *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XS_compute_acoustics_ReadReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XS_compute_acoustics_IsReady(XS_compute_acoustics *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XS_compute_acoustics_ReadReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XS_compute_acoustics_EnableAutoRestart(XS_compute_acoustics *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XS_compute_acoustics_WriteReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XS_compute_acoustics_DisableAutoRestart(XS_compute_acoustics *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XS_compute_acoustics_WriteReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XS_compute_acoustics_InterruptGlobalEnable(XS_compute_acoustics *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XS_compute_acoustics_WriteReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_GIE, 1);
}

void XS_compute_acoustics_InterruptGlobalDisable(XS_compute_acoustics *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XS_compute_acoustics_WriteReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_GIE, 0);
}

void XS_compute_acoustics_InterruptEnable(XS_compute_acoustics *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XS_compute_acoustics_ReadReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_IER);
    XS_compute_acoustics_WriteReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XS_compute_acoustics_InterruptDisable(XS_compute_acoustics *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XS_compute_acoustics_ReadReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_IER);
    XS_compute_acoustics_WriteReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XS_compute_acoustics_InterruptClear(XS_compute_acoustics *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XS_compute_acoustics_WriteReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XS_compute_acoustics_InterruptGetEnabled(XS_compute_acoustics *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XS_compute_acoustics_ReadReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_IER);
}

u32 XS_compute_acoustics_InterruptGetStatus(XS_compute_acoustics *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XS_compute_acoustics_ReadReg(InstancePtr->Control_bus_BaseAddress, XS_COMPUTE_ACOUSTICS_CONTROL_BUS_ADDR_ISR);
}

