// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xs_compute_acoustics.h"

extern XS_compute_acoustics_Config XS_compute_acoustics_ConfigTable[];

XS_compute_acoustics_Config *XS_compute_acoustics_LookupConfig(u16 DeviceId) {
	XS_compute_acoustics_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XS_COMPUTE_ACOUSTICS_NUM_INSTANCES; Index++) {
		if (XS_compute_acoustics_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XS_compute_acoustics_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XS_compute_acoustics_Initialize(XS_compute_acoustics *InstancePtr, u16 DeviceId) {
	XS_compute_acoustics_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XS_compute_acoustics_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XS_compute_acoustics_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

