#pragma line 1 "wave2/.apc/main.c" ::: 0
#pragma line 1 "wave2/.apc/main.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "wave2/.apc/main.c" 2 ::: 194
#pragma line 1 "wave2/.apc/acoustics.h" 1 ::: 195
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 196
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 224
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 258
#pragma line 147 "/usr/include/features.h" 3 4 ::: 378
#pragma line 218 "/usr/include/features.h" 3 4 ::: 425
#pragma line 230 "/usr/include/features.h" 3 4 ::: 428
#pragma line 271 "/usr/include/features.h" 3 4 ::: 451
#pragma line 300 "/usr/include/features.h" 3 4 ::: 455
#pragma line 406 "/usr/include/features.h" 3 4 ::: 462
#pragma line 437 "/usr/include/features.h" 3 4 ::: 485
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 489
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 524
#pragma line 440 "/usr/include/features.h" 2 3 4 ::: 531
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 554
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 595
#pragma line 88 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 601
#pragma line 122 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 627
#pragma line 138 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 629
#pragma line 162 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 640
#pragma line 189 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 650
#pragma line 249 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 703
#pragma line 267 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 714
#pragma line 313 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 748
#pragma line 359 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 778
#pragma line 383 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 795
#pragma line 434 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 799
#pragma line 452 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 801
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 802
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 804
#pragma line 453 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 806
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/long-double.h" 1 3 4 ::: 807
#pragma line 454 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 828
#pragma line 487 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 829
#pragma line 500 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 835
#pragma line 462 "/usr/include/features.h" 2 3 4 ::: 843
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 868
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 879
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 884
#pragma line 486 "/usr/include/features.h" 2 3 4 ::: 885
#pragma line 34 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 2 3 4 ::: 886
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 890
#pragma line 62 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 895
#pragma line 79 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 900
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 903
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 909
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 950
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 953
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 956
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 1005
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1007
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1035
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1037
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1039
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/timesize.h" 1 3 4 ::: 1040
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1064
#pragma line 136 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1144
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1151
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1169
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1174
#pragma line 142 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1195
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time64.h" 1 3 4 ::: 1196
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/time64.h" 3 4 ::: 1214
#pragma line 143 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1219
#pragma line 39 "/usr/include/stdio.h" 2 3 4 ::: 1296
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h" 1 3 4 ::: 1297
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h" 1 3 4 ::: 1302
#pragma line 6 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h" 2 3 4 ::: 1324
#pragma line 40 "/usr/include/stdio.h" 2 3 4 ::: 1334
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h" 1 3 4 ::: 1335
#pragma line 41 "/usr/include/stdio.h" 2 3 4 ::: 1350
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h" 1 3 4 ::: 1351
#pragma line 42 "/usr/include/stdio.h" 2 3 4 ::: 1357
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h" 1 3 4 ::: 1358
#pragma line 43 "/usr/include/stdio.h" 2 3 4 ::: 1366
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h" 1 3 4 ::: 1367
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h" 3 4 ::: 1391
#pragma line 118 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h" 3 4 ::: 1459
#pragma line 44 "/usr/include/stdio.h" 2 3 4 ::: 1461
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1471
#pragma line 77 "/usr/include/stdio.h" 3 4 ::: 1473
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1506
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1522
#pragma line 134 "/usr/include/stdio.h" 2 3 4 ::: 1539
#pragma line 168 "/usr/include/stdio.h" 3 4 ::: 1560
#pragma line 186 "/usr/include/stdio.h" 3 4 ::: 1567
#pragma line 242 "/usr/include/stdio.h" 3 4 ::: 1610
#pragma line 278 "/usr/include/stdio.h" 3 4 ::: 1624
#pragma line 291 "/usr/include/stdio.h" 3 4 ::: 1627
#pragma line 378 "/usr/include/stdio.h" 3 4 ::: 1698
#pragma line 428 "/usr/include/stdio.h" 3 4 ::: 1734
#pragma line 481 "/usr/include/stdio.h" 3 4 ::: 1771
#pragma line 593 "/usr/include/stdio.h" 3 4 ::: 1869
#pragma line 667 "/usr/include/stdio.h" 3 4 ::: 1931
#pragma line 727 "/usr/include/stdio.h" 3 4 ::: 1978
#pragma line 756 "/usr/include/stdio.h" 3 4 ::: 1989
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2016
#pragma line 782 "/usr/include/stdio.h" 2 3 4 ::: 2044
#pragma line 837 "/usr/include/stdio.h" 3 4 ::: 2076
#pragma line 856 "/usr/include/stdio.h" 3 4 ::: 2088
#pragma line 2 "wave2/.apc/acoustics.h" 2 ::: 2096
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2097
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 2123
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 2149
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 2152
#pragma line 62 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 2157
#pragma line 79 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 2162
#pragma line 26 "/usr/include/stdlib.h" 2 3 4 ::: 2165
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2172
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2197
#pragma line 32 "/usr/include/stdlib.h" 2 3 4 ::: 2200
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2209
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2238
#pragma line 40 "/usr/include/stdlib.h" 2 3 4 ::: 2256
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2257
#pragma line 41 "/usr/include/stdlib.h" 2 3 4 ::: 2313
#pragma line 54 "/usr/include/stdlib.h" 3 4 ::: 2316
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 1 3 4 ::: 2319
#pragma line 38 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 3 4 ::: 2348
#pragma line 70 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 3 4 ::: 2372
#pragma line 82 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 3 4 ::: 2374
#pragma line 120 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 3 4 ::: 2376
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 1 3 4 ::: 2377
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/long-double.h" 1 3 4 ::: 2402
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 2 3 4 ::: 2423
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2468
#pragma line 137 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2472
#pragma line 195 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2474
#pragma line 214 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2476
#pragma line 228 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2478
#pragma line 251 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2485
#pragma line 268 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2487
#pragma line 285 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2489
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 2 3 4 ::: 2491
#pragma line 56 "/usr/include/stdlib.h" 2 3 4 ::: 2492
#pragma line 175 "/usr/include/stdlib.h" 3 4 ::: 2569
#pragma line 382 "/usr/include/stdlib.h" 3 4 ::: 2606
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2620
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2641
#pragma line 59 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2657
#pragma line 97 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2679
#pragma line 114 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2687
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/clock_t.h" 1 3 4 ::: 2701
#pragma line 127 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2709
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/clockid_t.h" 1 3 4 ::: 2711
#pragma line 129 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2719
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/time_t.h" 1 3 4 ::: 2720
#pragma line 130 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2728
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/timer_t.h" 1 3 4 ::: 2729
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2737
#pragma line 144 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2738
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2739
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2764
#pragma line 145 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2767
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h" 1 3 4 ::: 2779
#pragma line 156 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2807
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2829
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2854
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endianness.h" 1 3 4 ::: 2890
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/endian.h" 2 3 4 ::: 2899
#pragma line 25 "/usr/include/endian.h" 2 3 4 ::: 2903
#pragma line 34 "/usr/include/endian.h" 3 4 ::: 2904
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2907
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2925
#pragma line 69 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2956
#pragma line 36 "/usr/include/endian.h" 2 3 4 ::: 2966
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/uintn-identity.h" 1 3 4 ::: 2967
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/uintn-identity.h" 3 4 ::: 2985
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 3007
#pragma line 177 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3008
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 3012
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 3043
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3066
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3068
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3070
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3071
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/sigset_t.h" 1 3 4 ::: 3075
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h" 1 3 4 ::: 3079
#pragma line 5 "/usr/include/x86_64-linux-gnu/bits/types/sigset_t.h" 2 3 4 ::: 3088
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3092
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h" 1 3 4 ::: 3097
#pragma line 38 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3110
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h" 1 3 4 ::: 3112
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h" 3 4 ::: 3129
#pragma line 40 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3131
#pragma line 93 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 3177
#pragma line 180 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3207
#pragma line 225 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3229
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3233
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h" 1 3 4 ::: 3257
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h" 1 3 4 ::: 3302
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3324
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3326
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h" 2 3 4 ::: 3328
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h" 2 3 4 ::: 3329
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/struct_mutex.h" 1 3 4 ::: 3360
#pragma line 53 "/usr/include/x86_64-linux-gnu/bits/struct_mutex.h" 3 4 ::: 3397
#pragma line 75 "/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h" 2 3 4 ::: 3399
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/struct_rwlock.h" 1 3 4 ::: 3413
#pragma line 55 "/usr/include/x86_64-linux-gnu/bits/struct_rwlock.h" 3 4 ::: 3459
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h" 2 3 4 ::: 3461
#pragma line 24 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3492
#pragma line 228 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3588
#pragma line 395 "/usr/include/stdlib.h" 2 3 4 ::: 3589
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3764
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3789
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3814
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3817
#pragma line 569 "/usr/include/stdlib.h" 2 3 4 ::: 3826
#pragma line 590 "/usr/include/stdlib.h" 3 4 ::: 3840
#pragma line 608 "/usr/include/stdlib.h" 3 4 ::: 3847
#pragma line 627 "/usr/include/stdlib.h" 3 4 ::: 3858
#pragma line 644 "/usr/include/stdlib.h" 3 4 ::: 3867
#pragma line 703 "/usr/include/stdlib.h" 3 4 ::: 3913
#pragma line 726 "/usr/include/stdlib.h" 3 4 ::: 3922
#pragma line 780 "/usr/include/stdlib.h" 3 4 ::: 3929
#pragma line 795 "/usr/include/stdlib.h" 3 4 ::: 3935
#pragma line 818 "/usr/include/stdlib.h" 3 4 ::: 3950
#pragma line 1000 "/usr/include/stdlib.h" 3 4 ::: 4098
#pragma line 1013 "/usr/include/stdlib.h" 3 4 ::: 4104
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4105
#pragma line 1014 "/usr/include/stdlib.h" 2 3 4 ::: 4123
#pragma line 3 "wave2/.apc/acoustics.h" 2 ::: 4126
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 4127
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 4155
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 4181
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 4184
#pragma line 62 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 4189
#pragma line 79 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 4194
#pragma line 28 "/usr/include/math.h" 2 3 4 ::: 4197
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 4211
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 4237
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 4269
#pragma line 41 "/usr/include/math.h" 2 3 4 ::: 4270
#pragma line 89 "/usr/include/math.h" 3 4 ::: 4277
#pragma line 137 "/usr/include/math.h" 3 4 ::: 4286
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/flt-eval-method.h" 1 3 4 ::: 4289
#pragma line 139 "/usr/include/math.h" 2 3 4 ::: 4307
#pragma line 180 "/usr/include/math.h" 3 4 ::: 4320
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/fp-logb.h" 1 3 4 ::: 4332
#pragma line 191 "/usr/include/math.h" 2 3 4 ::: 4350
#pragma line 221 "/usr/include/math.h" 3 4 ::: 4351
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/fp-fast.h" 1 3 4 ::: 4365
#pragma line 234 "/usr/include/math.h" 2 3 4 ::: 4392
#pragma line 257 "/usr/include/math.h" 3 4 ::: 4393
#pragma line 289 "/usr/include/math.h" 3 4 ::: 4398
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h" 1 3 4 ::: 4399
#pragma line 290 "/usr/include/math.h" 2 3 4 ::: 4443
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4444
#pragma line 84 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4520
#pragma line 210 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4639
#pragma line 271 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4692
#pragma line 289 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4703
#pragma line 399 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4751
#pragma line 291 "/usr/include/math.h" 2 3 4 ::: 4754
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h" 1 3 4 ::: 4771
#pragma line 307 "/usr/include/math.h" 2 3 4 ::: 4815
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4816
#pragma line 84 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4892
#pragma line 210 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5011
#pragma line 271 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5064
#pragma line 289 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5075
#pragma line 399 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5123
#pragma line 308 "/usr/include/math.h" 2 3 4 ::: 5126
#pragma line 341 "/usr/include/math.h" 3 4 ::: 5127
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h" 1 3 4 ::: 5137
#pragma line 350 "/usr/include/math.h" 2 3 4 ::: 5181
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 5182
#pragma line 84 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5258
#pragma line 210 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5377
#pragma line 271 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5430
#pragma line 289 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5441
#pragma line 399 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5489
#pragma line 351 "/usr/include/math.h" 2 3 4 ::: 5492
#pragma line 360 "/usr/include/math.h" 3 4 ::: 5493
#pragma line 486 "/usr/include/math.h" 3 4 ::: 5496
#pragma line 772 "/usr/include/math.h" 3 4 ::: 5498
#pragma line 785 "/usr/include/math.h" 3 4 ::: 5501
#pragma line 849 "/usr/include/math.h" 3 4 ::: 5511
#pragma line 910 "/usr/include/math.h" 3 4 ::: 5556
#pragma line 953 "/usr/include/math.h" 3 4 ::: 5583
#pragma line 1063 "/usr/include/math.h" 3 4 ::: 5593
#pragma line 1080 "/usr/include/math.h" 3 4 ::: 5595
#pragma line 1199 "/usr/include/math.h" 3 4 ::: 5599
#pragma line 1243 "/usr/include/math.h" 3 4 ::: 5615
#pragma line 4 "wave2/.apc/acoustics.h" 2 ::: 5617
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 5618
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 5645
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 5671
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 5674
#pragma line 62 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 5679
#pragma line 79 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 5684
#pragma line 27 "/usr/include/string.h" 2 3 4 ::: 5687
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5695
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5720
#pragma line 34 "/usr/include/string.h" 2 3 4 ::: 5723
#pragma line 91 "/usr/include/string.h" 3 4 ::: 5758
#pragma line 121 "/usr/include/string.h" 3 4 ::: 5761
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/locale_t.h" 1 3 4 ::: 5795
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__locale_t.h" 1 3 4 ::: 5818
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/types/locale_t.h" 2 3 4 ::: 5861
#pragma line 154 "/usr/include/string.h" 2 3 4 ::: 5864
#pragma line 202 "/usr/include/string.h" 3 4 ::: 5888
#pragma line 226 "/usr/include/string.h" 3 4 ::: 5890
#pragma line 253 "/usr/include/string.h" 3 4 ::: 5895
#pragma line 271 "/usr/include/string.h" 3 4 ::: 5898
#pragma line 303 "/usr/include/string.h" 3 4 ::: 5908
#pragma line 330 "/usr/include/string.h" 3 4 ::: 5913
#pragma line 384 "/usr/include/string.h" 3 4 ::: 5933
#pragma line 427 "/usr/include/string.h" 3 4 ::: 5961
#pragma line 1 "/usr/include/strings.h" 1 3 4 ::: 5968
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5992
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6017
#pragma line 24 "/usr/include/strings.h" 2 3 4 ::: 6020
#pragma line 68 "/usr/include/strings.h" 3 4 ::: 6042
#pragma line 96 "/usr/include/strings.h" 3 4 ::: 6048
#pragma line 433 "/usr/include/string.h" 2 3 4 ::: 6089
#pragma line 5 "wave2/.apc/acoustics.h" 2 ::: 6120
#pragma line 1 "/usr/include/unistd.h" 1 3 4 ::: 6121
#pragma line 29 "/usr/include/unistd.h" 3 4 ::: 6142
#pragma line 49 "/usr/include/unistd.h" 3 4 ::: 6148
#pragma line 66 "/usr/include/unistd.h" 3 4 ::: 6155
#pragma line 99 "/usr/include/unistd.h" 3 4 ::: 6179
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix_opt.h" 1 3 4 ::: 6284
#pragma line 203 "/usr/include/unistd.h" 2 3 4 ::: 6476
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/environments.h" 1 3 4 ::: 6481
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 6504
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 6506
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/environments.h" 2 3 4 ::: 6508
#pragma line 207 "/usr/include/unistd.h" 2 3 4 ::: 6547
#pragma line 226 "/usr/include/unistd.h" 3 4 ::: 6557
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 6558
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6583
#pragma line 227 "/usr/include/unistd.h" 2 3 4 ::: 6586
#pragma line 255 "/usr/include/unistd.h" 3 4 ::: 6591
#pragma line 267 "/usr/include/unistd.h" 3 4 ::: 6593
#pragma line 301 "/usr/include/unistd.h" 3 4 ::: 6615
#pragma line 321 "/usr/include/unistd.h" 3 4 ::: 6625
#pragma line 349 "/usr/include/unistd.h" 3 4 ::: 6640
#pragma line 413 "/usr/include/unistd.h" 3 4 ::: 6678
#pragma line 522 "/usr/include/unistd.h" 3 4 ::: 6778
#pragma line 597 "/usr/include/unistd.h" 3 4 ::: 6843
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/confname.h" 1 3 4 ::: 6857
#pragma line 610 "/usr/include/unistd.h" 2 3 4 ::: 7533
#pragma line 753 "/usr/include/unistd.h" 3 4 ::: 7652
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/getopt_posix.h" 1 3 4 ::: 7770
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/getopt_posix.h" 3 4 ::: 7789
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/getopt_core.h" 1 3 4 ::: 7790
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/getopt_posix.h" 2 3 4 ::: 7883
#pragma line 870 "/usr/include/unistd.h" 2 3 4 ::: 7884
#pragma line 966 "/usr/include/unistd.h" 3 4 ::: 7970
#pragma line 1012 "/usr/include/unistd.h" 3 4 ::: 7998
#pragma line 1033 "/usr/include/unistd.h" 3 4 ::: 8002
#pragma line 1113 "/usr/include/unistd.h" 3 4 ::: 8050
#pragma line 1138 "/usr/include/unistd.h" 3 4 ::: 8064
#pragma line 1150 "/usr/include/unistd.h" 3 4 ::: 8068
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/unistd_ext.h" 1 3 4 ::: 8090
#pragma line 1171 "/usr/include/unistd.h" 2 3 4 ::: 8108
#pragma line 6 "wave2/.apc/acoustics.h" 2 ::: 8109
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 8110
#pragma line 29 "/usr/include/time.h" 3 4 ::: 8131
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 8132
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 8157
#pragma line 30 "/usr/include/time.h" 2 3 4 ::: 8160
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 8165
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/time.h" 3 4 ::: 8199
#pragma line 34 "/usr/include/time.h" 2 3 4 ::: 8224
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_tm.h" 1 3 4 ::: 8231
#pragma line 40 "/usr/include/time.h" 2 3 4 ::: 8258
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_itimerspec.h" 1 3 4 ::: 8267
#pragma line 49 "/usr/include/time.h" 2 3 4 ::: 8280
#pragma line 70 "/usr/include/time.h" 3 4 ::: 8282
#pragma line 101 "/usr/include/time.h" 3 4 ::: 8304
#pragma line 117 "/usr/include/time.h" 3 4 ::: 8312
#pragma line 7 "wave2/.apc/acoustics.h" 2 ::: 8448
#pragma line 2 "wave2/.apc/main.c" 2 ::: 8532
