#pragma line 1 "wave2/.apc/main.c" ::: -10
#pragma line 1 "wave2/.apc/main.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "wave2/.apc/main.c" 2 ::: 184
#pragma line 1 "wave2/.apc/acoustics.h" 1 ::: 185
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 186
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 214
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 248
#pragma line 147 "/usr/include/features.h" 3 4 ::: 368
#pragma line 218 "/usr/include/features.h" 3 4 ::: 415
#pragma line 230 "/usr/include/features.h" 3 4 ::: 418
#pragma line 271 "/usr/include/features.h" 3 4 ::: 441
#pragma line 300 "/usr/include/features.h" 3 4 ::: 445
#pragma line 406 "/usr/include/features.h" 3 4 ::: 452
#pragma line 437 "/usr/include/features.h" 3 4 ::: 475
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 479
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 514
#pragma line 440 "/usr/include/features.h" 2 3 4 ::: 521
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 544
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 585
#pragma line 88 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 591
#pragma line 122 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 617
#pragma line 138 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 619
#pragma line 162 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 630
#pragma line 189 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 640
#pragma line 249 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 693
#pragma line 267 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 704
#pragma line 313 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 738
#pragma line 359 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 768
#pragma line 383 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 785
#pragma line 434 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 789
#pragma line 452 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 791
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 792
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 794
#pragma line 453 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 796
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/long-double.h" 1 3 4 ::: 797
#pragma line 454 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 818
#pragma line 487 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 819
#pragma line 500 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 825
#pragma line 462 "/usr/include/features.h" 2 3 4 ::: 833
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 858
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 869
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 874
#pragma line 486 "/usr/include/features.h" 2 3 4 ::: 875
#pragma line 34 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 2 3 4 ::: 876
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 880
#pragma line 62 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 885
#pragma line 79 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 890
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 893
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 899
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 940
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 943
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 946
#pragma line 37 "/usr/include/stdio.h" 2 3 4 ::: 995
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 997
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1025
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1027
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1029
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/timesize.h" 1 3 4 ::: 1030
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1054
#pragma line 136 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1134
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1141
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1159
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1164
#pragma line 142 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1185
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time64.h" 1 3 4 ::: 1186
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/time64.h" 3 4 ::: 1204
#pragma line 143 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1209
#pragma line 39 "/usr/include/stdio.h" 2 3 4 ::: 1286
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h" 1 3 4 ::: 1287
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h" 1 3 4 ::: 1292
#pragma line 6 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h" 2 3 4 ::: 1314
#pragma line 40 "/usr/include/stdio.h" 2 3 4 ::: 1324
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h" 1 3 4 ::: 1325
#pragma line 41 "/usr/include/stdio.h" 2 3 4 ::: 1340
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h" 1 3 4 ::: 1341
#pragma line 42 "/usr/include/stdio.h" 2 3 4 ::: 1347
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h" 1 3 4 ::: 1348
#pragma line 43 "/usr/include/stdio.h" 2 3 4 ::: 1356
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h" 1 3 4 ::: 1357
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h" 3 4 ::: 1381
#pragma line 118 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h" 3 4 ::: 1449
#pragma line 44 "/usr/include/stdio.h" 2 3 4 ::: 1451
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1461
#pragma line 77 "/usr/include/stdio.h" 3 4 ::: 1463
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1496
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1512
#pragma line 134 "/usr/include/stdio.h" 2 3 4 ::: 1529
#pragma line 168 "/usr/include/stdio.h" 3 4 ::: 1550
#pragma line 186 "/usr/include/stdio.h" 3 4 ::: 1557
#pragma line 242 "/usr/include/stdio.h" 3 4 ::: 1600
#pragma line 278 "/usr/include/stdio.h" 3 4 ::: 1614
#pragma line 291 "/usr/include/stdio.h" 3 4 ::: 1617
#pragma line 378 "/usr/include/stdio.h" 3 4 ::: 1688
#pragma line 428 "/usr/include/stdio.h" 3 4 ::: 1724
#pragma line 481 "/usr/include/stdio.h" 3 4 ::: 1761
#pragma line 593 "/usr/include/stdio.h" 3 4 ::: 1859
#pragma line 667 "/usr/include/stdio.h" 3 4 ::: 1921
#pragma line 727 "/usr/include/stdio.h" 3 4 ::: 1968
#pragma line 756 "/usr/include/stdio.h" 3 4 ::: 1979
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2006
#pragma line 782 "/usr/include/stdio.h" 2 3 4 ::: 2034
#pragma line 837 "/usr/include/stdio.h" 3 4 ::: 2066
#pragma line 856 "/usr/include/stdio.h" 3 4 ::: 2078
#pragma line 2 "wave2/.apc/acoustics.h" 2 ::: 2086
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2087
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 2113
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 2139
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 2142
#pragma line 62 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 2147
#pragma line 79 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 2152
#pragma line 26 "/usr/include/stdlib.h" 2 3 4 ::: 2155
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2162
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2187
#pragma line 32 "/usr/include/stdlib.h" 2 3 4 ::: 2190
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2199
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2228
#pragma line 40 "/usr/include/stdlib.h" 2 3 4 ::: 2246
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2247
#pragma line 41 "/usr/include/stdlib.h" 2 3 4 ::: 2303
#pragma line 54 "/usr/include/stdlib.h" 3 4 ::: 2306
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 1 3 4 ::: 2309
#pragma line 38 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 3 4 ::: 2338
#pragma line 70 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 3 4 ::: 2362
#pragma line 82 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 3 4 ::: 2364
#pragma line 120 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 3 4 ::: 2366
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 1 3 4 ::: 2367
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/long-double.h" 1 3 4 ::: 2392
#pragma line 25 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 2 3 4 ::: 2413
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2458
#pragma line 137 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2462
#pragma line 195 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2464
#pragma line 214 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2466
#pragma line 228 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2468
#pragma line 251 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2475
#pragma line 268 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2477
#pragma line 285 "/usr/include/x86_64-linux-gnu/bits/floatn-common.h" 3 4 ::: 2479
#pragma line 121 "/usr/include/x86_64-linux-gnu/bits/floatn.h" 2 3 4 ::: 2481
#pragma line 56 "/usr/include/stdlib.h" 2 3 4 ::: 2482
#pragma line 175 "/usr/include/stdlib.h" 3 4 ::: 2559
#pragma line 382 "/usr/include/stdlib.h" 3 4 ::: 2596
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2610
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2631
#pragma line 59 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2647
#pragma line 97 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2669
#pragma line 114 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2677
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/clock_t.h" 1 3 4 ::: 2691
#pragma line 127 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2699
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/clockid_t.h" 1 3 4 ::: 2701
#pragma line 129 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2709
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/time_t.h" 1 3 4 ::: 2710
#pragma line 130 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2718
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/timer_t.h" 1 3 4 ::: 2719
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2727
#pragma line 144 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2728
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2729
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2754
#pragma line 145 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2757
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h" 1 3 4 ::: 2769
#pragma line 156 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2797
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2819
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2844
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endianness.h" 1 3 4 ::: 2880
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/endian.h" 2 3 4 ::: 2889
#pragma line 25 "/usr/include/endian.h" 2 3 4 ::: 2893
#pragma line 34 "/usr/include/endian.h" 3 4 ::: 2894
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2897
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2915
#pragma line 69 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2946
#pragma line 36 "/usr/include/endian.h" 2 3 4 ::: 2956
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/uintn-identity.h" 1 3 4 ::: 2957
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/uintn-identity.h" 3 4 ::: 2975
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2997
#pragma line 177 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2998
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 3002
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 3033
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3056
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3058
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3060
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3061
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/sigset_t.h" 1 3 4 ::: 3065
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h" 1 3 4 ::: 3069
#pragma line 5 "/usr/include/x86_64-linux-gnu/bits/types/sigset_t.h" 2 3 4 ::: 3078
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3082
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h" 1 3 4 ::: 3087
#pragma line 38 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3100
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h" 1 3 4 ::: 3102
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h" 3 4 ::: 3119
#pragma line 40 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3121
#pragma line 93 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 3167
#pragma line 180 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3197
#pragma line 225 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3219
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3223
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h" 1 3 4 ::: 3247
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h" 1 3 4 ::: 3292
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3314
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3316
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h" 2 3 4 ::: 3318
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h" 2 3 4 ::: 3319
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/struct_mutex.h" 1 3 4 ::: 3350
#pragma line 53 "/usr/include/x86_64-linux-gnu/bits/struct_mutex.h" 3 4 ::: 3387
#pragma line 75 "/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h" 2 3 4 ::: 3389
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/struct_rwlock.h" 1 3 4 ::: 3403
#pragma line 55 "/usr/include/x86_64-linux-gnu/bits/struct_rwlock.h" 3 4 ::: 3449
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h" 2 3 4 ::: 3451
#pragma line 24 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3482
#pragma line 228 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3578
#pragma line 395 "/usr/include/stdlib.h" 2 3 4 ::: 3579
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3754
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3779
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3804
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3807
#pragma line 569 "/usr/include/stdlib.h" 2 3 4 ::: 3816
#pragma line 590 "/usr/include/stdlib.h" 3 4 ::: 3830
#pragma line 608 "/usr/include/stdlib.h" 3 4 ::: 3837
#pragma line 627 "/usr/include/stdlib.h" 3 4 ::: 3848
#pragma line 644 "/usr/include/stdlib.h" 3 4 ::: 3857
#pragma line 703 "/usr/include/stdlib.h" 3 4 ::: 3903
#pragma line 726 "/usr/include/stdlib.h" 3 4 ::: 3912
#pragma line 780 "/usr/include/stdlib.h" 3 4 ::: 3919
#pragma line 795 "/usr/include/stdlib.h" 3 4 ::: 3925
#pragma line 818 "/usr/include/stdlib.h" 3 4 ::: 3940
#pragma line 1000 "/usr/include/stdlib.h" 3 4 ::: 4088
#pragma line 1013 "/usr/include/stdlib.h" 3 4 ::: 4094
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4095
#pragma line 1014 "/usr/include/stdlib.h" 2 3 4 ::: 4113
#pragma line 3 "wave2/.apc/acoustics.h" 2 ::: 4116
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 4117
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 4145
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 4171
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 4174
#pragma line 62 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 4179
#pragma line 79 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 4184
#pragma line 28 "/usr/include/math.h" 2 3 4 ::: 4187
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 4201
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 4227
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 4259
#pragma line 41 "/usr/include/math.h" 2 3 4 ::: 4260
#pragma line 89 "/usr/include/math.h" 3 4 ::: 4267
#pragma line 137 "/usr/include/math.h" 3 4 ::: 4276
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/flt-eval-method.h" 1 3 4 ::: 4279
#pragma line 139 "/usr/include/math.h" 2 3 4 ::: 4297
#pragma line 180 "/usr/include/math.h" 3 4 ::: 4310
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/fp-logb.h" 1 3 4 ::: 4322
#pragma line 191 "/usr/include/math.h" 2 3 4 ::: 4340
#pragma line 221 "/usr/include/math.h" 3 4 ::: 4341
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/fp-fast.h" 1 3 4 ::: 4355
#pragma line 234 "/usr/include/math.h" 2 3 4 ::: 4382
#pragma line 257 "/usr/include/math.h" 3 4 ::: 4383
#pragma line 289 "/usr/include/math.h" 3 4 ::: 4388
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h" 1 3 4 ::: 4389
#pragma line 290 "/usr/include/math.h" 2 3 4 ::: 4433
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4434
#pragma line 84 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4510
#pragma line 210 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4629
#pragma line 271 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4682
#pragma line 289 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4693
#pragma line 399 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4741
#pragma line 291 "/usr/include/math.h" 2 3 4 ::: 4744
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h" 1 3 4 ::: 4761
#pragma line 307 "/usr/include/math.h" 2 3 4 ::: 4805
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4806
#pragma line 84 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4882
#pragma line 210 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5001
#pragma line 271 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5054
#pragma line 289 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5065
#pragma line 399 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5113
#pragma line 308 "/usr/include/math.h" 2 3 4 ::: 5116
#pragma line 341 "/usr/include/math.h" 3 4 ::: 5117
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h" 1 3 4 ::: 5127
#pragma line 350 "/usr/include/math.h" 2 3 4 ::: 5171
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 5172
#pragma line 84 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5248
#pragma line 210 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5367
#pragma line 271 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5420
#pragma line 289 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5431
#pragma line 399 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5479
#pragma line 351 "/usr/include/math.h" 2 3 4 ::: 5482
#pragma line 360 "/usr/include/math.h" 3 4 ::: 5483
#pragma line 486 "/usr/include/math.h" 3 4 ::: 5486
#pragma line 772 "/usr/include/math.h" 3 4 ::: 5488
#pragma line 785 "/usr/include/math.h" 3 4 ::: 5491
#pragma line 849 "/usr/include/math.h" 3 4 ::: 5501
#pragma line 910 "/usr/include/math.h" 3 4 ::: 5546
#pragma line 953 "/usr/include/math.h" 3 4 ::: 5573
#pragma line 1063 "/usr/include/math.h" 3 4 ::: 5583
#pragma line 1080 "/usr/include/math.h" 3 4 ::: 5585
#pragma line 1199 "/usr/include/math.h" 3 4 ::: 5589
#pragma line 1243 "/usr/include/math.h" 3 4 ::: 5605
#pragma line 4 "wave2/.apc/acoustics.h" 2 ::: 5607
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 5608
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 1 3 4 ::: 5635
#pragma line 35 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 5661
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 5664
#pragma line 62 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 5669
#pragma line 79 "/usr/include/x86_64-linux-gnu/bits/libc-header-start.h" 3 4 ::: 5674
#pragma line 27 "/usr/include/string.h" 2 3 4 ::: 5677
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5685
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5710
#pragma line 34 "/usr/include/string.h" 2 3 4 ::: 5713
#pragma line 91 "/usr/include/string.h" 3 4 ::: 5748
#pragma line 121 "/usr/include/string.h" 3 4 ::: 5751
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/locale_t.h" 1 3 4 ::: 5785
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/__locale_t.h" 1 3 4 ::: 5808
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/types/locale_t.h" 2 3 4 ::: 5851
#pragma line 154 "/usr/include/string.h" 2 3 4 ::: 5854
#pragma line 202 "/usr/include/string.h" 3 4 ::: 5878
#pragma line 226 "/usr/include/string.h" 3 4 ::: 5880
#pragma line 253 "/usr/include/string.h" 3 4 ::: 5885
#pragma line 271 "/usr/include/string.h" 3 4 ::: 5888
#pragma line 303 "/usr/include/string.h" 3 4 ::: 5898
#pragma line 330 "/usr/include/string.h" 3 4 ::: 5903
#pragma line 384 "/usr/include/string.h" 3 4 ::: 5923
#pragma line 427 "/usr/include/string.h" 3 4 ::: 5951
#pragma line 1 "/usr/include/strings.h" 1 3 4 ::: 5958
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5982
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6007
#pragma line 24 "/usr/include/strings.h" 2 3 4 ::: 6010
#pragma line 68 "/usr/include/strings.h" 3 4 ::: 6032
#pragma line 96 "/usr/include/strings.h" 3 4 ::: 6038
#pragma line 433 "/usr/include/string.h" 2 3 4 ::: 6079
#pragma line 5 "wave2/.apc/acoustics.h" 2 ::: 6110
#pragma line 1 "/usr/include/unistd.h" 1 3 4 ::: 6111
#pragma line 29 "/usr/include/unistd.h" 3 4 ::: 6132
#pragma line 49 "/usr/include/unistd.h" 3 4 ::: 6138
#pragma line 66 "/usr/include/unistd.h" 3 4 ::: 6145
#pragma line 99 "/usr/include/unistd.h" 3 4 ::: 6169
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix_opt.h" 1 3 4 ::: 6274
#pragma line 203 "/usr/include/unistd.h" 2 3 4 ::: 6466
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/environments.h" 1 3 4 ::: 6471
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 6494
#pragma line 13 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 6496
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/environments.h" 2 3 4 ::: 6498
#pragma line 207 "/usr/include/unistd.h" 2 3 4 ::: 6537
#pragma line 226 "/usr/include/unistd.h" 3 4 ::: 6547
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 6548
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6573
#pragma line 227 "/usr/include/unistd.h" 2 3 4 ::: 6576
#pragma line 255 "/usr/include/unistd.h" 3 4 ::: 6581
#pragma line 267 "/usr/include/unistd.h" 3 4 ::: 6583
#pragma line 301 "/usr/include/unistd.h" 3 4 ::: 6605
#pragma line 321 "/usr/include/unistd.h" 3 4 ::: 6615
#pragma line 349 "/usr/include/unistd.h" 3 4 ::: 6630
#pragma line 413 "/usr/include/unistd.h" 3 4 ::: 6668
#pragma line 522 "/usr/include/unistd.h" 3 4 ::: 6768
#pragma line 597 "/usr/include/unistd.h" 3 4 ::: 6833
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/confname.h" 1 3 4 ::: 6847
#pragma line 610 "/usr/include/unistd.h" 2 3 4 ::: 7523
#pragma line 753 "/usr/include/unistd.h" 3 4 ::: 7642
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/getopt_posix.h" 1 3 4 ::: 7760
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/getopt_posix.h" 3 4 ::: 7779
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/getopt_core.h" 1 3 4 ::: 7780
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/getopt_posix.h" 2 3 4 ::: 7873
#pragma line 870 "/usr/include/unistd.h" 2 3 4 ::: 7874
#pragma line 966 "/usr/include/unistd.h" 3 4 ::: 7960
#pragma line 1012 "/usr/include/unistd.h" 3 4 ::: 7988
#pragma line 1033 "/usr/include/unistd.h" 3 4 ::: 7992
#pragma line 1113 "/usr/include/unistd.h" 3 4 ::: 8040
#pragma line 1138 "/usr/include/unistd.h" 3 4 ::: 8054
#pragma line 1150 "/usr/include/unistd.h" 3 4 ::: 8058
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/unistd_ext.h" 1 3 4 ::: 8080
#pragma line 1171 "/usr/include/unistd.h" 2 3 4 ::: 8098
#pragma line 6 "wave2/.apc/acoustics.h" 2 ::: 8099
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 8100
#pragma line 29 "/usr/include/time.h" 3 4 ::: 8121
#pragma line 1 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 8122
#pragma line 56 "/media/dorin/3cecc5e0-a48f-49e8-a0d0-1f839df07f65/home/dorin/Xilinx-Emil/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 8147
#pragma line 30 "/usr/include/time.h" 2 3 4 ::: 8150
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 8155
#pragma line 45 "/usr/include/x86_64-linux-gnu/bits/time.h" 3 4 ::: 8189
#pragma line 34 "/usr/include/time.h" 2 3 4 ::: 8214
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_tm.h" 1 3 4 ::: 8221
#pragma line 40 "/usr/include/time.h" 2 3 4 ::: 8248
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types/struct_itimerspec.h" 1 3 4 ::: 8257
#pragma line 49 "/usr/include/time.h" 2 3 4 ::: 8270
#pragma line 70 "/usr/include/time.h" 3 4 ::: 8272
#pragma line 101 "/usr/include/time.h" 3 4 ::: 8294
#pragma line 117 "/usr/include/time.h" 3 4 ::: 8302
#pragma line 7 "wave2/.apc/acoustics.h" 2 ::: 8438
#pragma line 2 "wave2/.apc/main.c" 2 ::: 8522
