// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sin_cos_range_redux_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        t_in,
        ap_return
);

parameter    ap_ST_fsm_state1 = 11'b1;
parameter    ap_ST_fsm_state2 = 11'b10;
parameter    ap_ST_fsm_state3 = 11'b100;
parameter    ap_ST_fsm_state4 = 11'b1000;
parameter    ap_ST_fsm_state5 = 11'b10000;
parameter    ap_ST_fsm_state6 = 11'b100000;
parameter    ap_ST_fsm_state7 = 11'b1000000;
parameter    ap_ST_fsm_state8 = 11'b10000000;
parameter    ap_ST_fsm_state9 = 11'b100000000;
parameter    ap_ST_fsm_state10 = 11'b1000000000;
parameter    ap_ST_fsm_state11 = 11'b10000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv79_0 = 79'b0000000000000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv79_9B74EDA8435E5A67F5F = 79'b1001101101110100111011011010100001000011010111100101101001100111111101011111;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_34 = 32'b110100;
parameter    ap_const_lv32_3E = 32'b111110;
parameter    ap_const_lv12_C01 = 12'b110000000001;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv12_C4D = 12'b110001001101;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv25_0 = 25'b0000000000000000000000000;
parameter    ap_const_lv12_3FE = 12'b1111111110;
parameter    ap_const_lv32_83 = 32'b10000011;
parameter    ap_const_lv32_FF = 32'b11111111;
parameter    ap_const_lv32_2C = 32'b101100;
parameter    ap_const_lv32_79 = 32'b1111001;
parameter    ap_const_lv32_7A = 32'b1111010;
parameter    ap_const_lv32_7C = 32'b1111100;
parameter    ap_const_lv32_4D = 32'b1001101;
parameter    ap_const_lv32_9B = 32'b10011011;
parameter    ap_const_lv79_6487ED5110B4611A6263 = 79'b1100100100001111110110101010001000100001011010001100001000110100110001001100011;
parameter    ap_const_lv32_4E = 32'b1001110;
parameter    ap_const_lv7_4E = 7'b1001110;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv76_0 = 76'b0000000000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv78_0 = 78'b000000000000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv78_20000000000000000000 = 78'b100000000000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_2E = 32'b101110;
parameter    ap_const_lv32_3D = 32'b111101;
parameter    ap_const_lv16_8000 = 16'b1000000000000000;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_2D = 32'b101101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv11_3E7 = 11'b1111100111;
parameter    ap_const_lv32_32 = 32'b110010;
parameter    ap_const_lv32_7D = 32'b1111101;
parameter    ap_const_lv32_31 = 32'b110001;
parameter    ap_const_lv77_0 = 77'b00000000000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv11_10 = 11'b10000;
parameter    ap_const_lv11_3FF = 11'b1111111111;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv32_4C = 32'b1001100;
parameter    ap_const_lv64_8000000000000000 = 64'b1000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv3_6 = 3'b110;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv64_7FFFFFFFFFFFFFFF = 64'b111111111111111111111111111111111111111111111111111111111111111;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] t_in;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
wire   [3:0] hls_ref_4oPi_table_s_address0;
reg    hls_ref_4oPi_table_s_ce0;
wire   [255:0] hls_ref_4oPi_table_s_q0;
wire   [6:0] hls_cordic_ctab_tab_address0;
reg    hls_cordic_ctab_tab_ce0;
wire   [125:0] hls_cordic_ctab_tab_q0;
reg   [0:0] p_Result_s_reg_1482;
wire   [10:0] loc_V_fu_319_p4;
reg   [10:0] loc_V_reg_1487;
wire   [51:0] loc_V_1_fu_329_p1;
reg   [51:0] loc_V_1_reg_1493;
wire   [0:0] tmp_3_fu_343_p3;
reg   [0:0] tmp_3_reg_1498;
wire   [6:0] tmp_4_fu_372_p1;
reg   [6:0] tmp_4_reg_1507;
wire   [77:0] tmp_223_i_i_fu_400_p2;
wire   [52:0] r_V_5_fu_406_p3;
reg   [52:0] r_V_5_reg_1517;
wire   [0:0] ap_CS_fsm_state2;
reg   [124:0] ret_V_5_reg_1522;
reg   [77:0] h_fract_V_reg_1527;
wire   [0:0] ap_CS_fsm_state3;
wire    grp_big_mult_v3small_fu_301_ap_done;
reg   [2:0] p_Val2_9_reg_1532;
reg   [0:0] tmp_5_reg_1537;
wire   [75:0] r_V_7_fu_507_p4;
reg   [75:0] r_V_7_reg_1542;
wire   [0:0] ap_CS_fsm_state4;
wire    grp_big_mult_v3_94_17_s_fu_296_ap_done;
wire   [78:0] loc_V_2_fu_517_p1;
wire   [6:0] k_fu_527_p2;
reg   [6:0] k_reg_1555;
wire   [0:0] ap_CS_fsm_state5;
wire   [78:0] y_s_V_fu_537_p2;
reg   [78:0] y_s_V_reg_1560;
wire   [0:0] exitcond_i_fu_521_p2;
wire   [78:0] x_s_V_fu_543_p2;
reg   [78:0] x_s_V_reg_1566;
wire   [77:0] p_Val2_13_fu_583_p3;
reg   [77:0] p_Val2_13_reg_1577;
wire   [77:0] p_Val2_16_fu_591_p3;
reg   [77:0] p_Val2_16_reg_1583;
reg   [15:0] p_Result_i1_reg_1589;
reg   [15:0] p_Result_8_i_reg_1594;
reg   [31:0] c2_fu_655_p3;
reg   [31:0] c2_reg_1599;
reg   [31:0] c3_fu_663_p3;
reg   [31:0] c3_reg_1606;
wire   [10:0] tmp_9_fu_671_p1;
reg   [10:0] tmp_9_reg_1613;
reg   [15:0] p_Result_i2_reg_1618;
reg   [15:0] p_Result_8_i1_reg_1623;
reg   [31:0] c2_1_fu_731_p3;
reg   [31:0] c2_1_reg_1628;
reg   [31:0] c3_1_fu_739_p3;
reg   [31:0] c3_1_reg_1635;
wire   [10:0] tmp_33_fu_747_p1;
reg   [10:0] tmp_33_reg_1642;
wire   [2:0] sel_fu_757_p3;
reg   [2:0] sel_reg_1647;
wire   [0:0] tmp_26_fu_764_p2;
reg   [0:0] tmp_26_reg_1657;
wire   [0:0] tmp_27_fu_769_p2;
reg   [0:0] tmp_27_reg_1662;
wire   [0:0] d_V_fu_774_p3;
reg   [0:0] d_V_reg_1667;
wire   [0:0] ap_CS_fsm_state6;
wire   [78:0] tx_V_fu_794_p2;
reg   [78:0] tx_V_reg_1672;
wire   [78:0] ty_V_fu_812_p2;
reg   [78:0] ty_V_reg_1677;
wire   [75:0] p_Val2_27_fu_840_p2;
reg   [75:0] p_Val2_27_reg_1682;
wire   [78:0] tz_V_fu_866_p2;
wire   [0:0] ap_CS_fsm_state7;
reg   [31:0] c4_fu_894_p3;
reg   [31:0] c4_reg_1692;
wire   [0:0] ap_CS_fsm_state8;
wire   [77:0] tmp_i1_35_fu_906_p2;
reg   [77:0] tmp_i1_35_reg_1697;
wire   [0:0] tmp_197_i_fu_911_p2;
reg   [0:0] tmp_197_i_reg_1703;
wire   [0:0] tmp_200_i_fu_922_p2;
reg   [0:0] tmp_200_i_reg_1709;
wire   [0:0] sel_tmp1_i_fu_949_p2;
reg   [0:0] sel_tmp1_i_reg_1714;
wire   [10:0] tmp_19_fu_975_p3;
reg   [10:0] tmp_19_reg_1719;
wire   [0:0] tmp_206_i_fu_983_p2;
reg   [0:0] tmp_206_i_reg_1724;
reg   [31:0] c4_1_fu_1010_p3;
reg   [31:0] c4_1_reg_1729;
wire   [77:0] tmp_i2_fu_1022_p2;
reg   [77:0] tmp_i2_reg_1734;
wire   [0:0] tmp_197_i1_fu_1027_p2;
reg   [0:0] tmp_197_i1_reg_1740;
wire   [0:0] tmp_200_i1_fu_1038_p2;
reg   [0:0] tmp_200_i1_reg_1746;
wire   [0:0] sel_tmp1_i1_fu_1065_p2;
reg   [0:0] sel_tmp1_i1_reg_1751;
wire   [10:0] tmp_38_fu_1091_p3;
reg   [10:0] tmp_38_reg_1756;
wire   [0:0] tmp_206_i1_fu_1099_p2;
reg   [0:0] tmp_206_i1_reg_1761;
wire   [77:0] tmp_199_i_fu_1107_p2;
reg   [77:0] tmp_199_i_reg_1766;
wire   [0:0] ap_CS_fsm_state9;
wire   [0:0] sel_tmp6_i_fu_1117_p2;
reg   [0:0] sel_tmp6_i_reg_1772;
wire   [10:0] out_exp_V_fu_1140_p3;
reg   [10:0] out_exp_V_reg_1777;
wire   [77:0] tmp_199_i1_fu_1150_p2;
reg   [77:0] tmp_199_i1_reg_1782;
wire   [0:0] sel_tmp6_i1_fu_1160_p2;
reg   [0:0] sel_tmp6_i1_reg_1788;
wire   [10:0] out_exp_V_1_fu_1183_p3;
reg   [10:0] out_exp_V_1_reg_1793;
wire   [51:0] loc_V_3_fu_1259_p3;
reg   [51:0] loc_V_3_reg_1798;
wire   [0:0] ap_CS_fsm_state10;
wire   [51:0] loc_V_4_fu_1335_p3;
reg   [51:0] loc_V_4_reg_1803;
wire    grp_big_mult_v3_94_17_s_fu_296_ap_start;
wire    grp_big_mult_v3_94_17_s_fu_296_ap_idle;
wire    grp_big_mult_v3_94_17_s_fu_296_ap_ready;
wire   [187:0] grp_big_mult_v3_94_17_s_fu_296_ap_return;
wire    grp_big_mult_v3small_fu_301_ap_start;
wire    grp_big_mult_v3small_fu_301_ap_idle;
wire    grp_big_mult_v3small_fu_301_ap_ready;
wire   [177:0] grp_big_mult_v3small_fu_301_ap_return;
reg   [2:0] k_V_reg_230;
wire   [77:0] tmp_135_i_fu_499_p3;
reg   [77:0] dout_V_phi_fu_245_p4;
reg   [77:0] dout_V_reg_242;
reg   [78:0] p_Val2_7_reg_251;
reg   [78:0] p_Val2_6_reg_261;
reg   [78:0] p_Val2_5_reg_273;
reg   [6:0] sh_assign_reg_285;
reg    ap_reg_grp_big_mult_v3_94_17_s_fu_296_ap_start;
reg    ap_reg_grp_big_mult_v3small_fu_301_ap_start;
wire   [63:0] tmp_i_i_fu_367_p1;
wire   [63:0] tmp_28_fu_549_p1;
wire   [63:0] p_Val2_3_fu_307_p1;
wire   [11:0] tmp_i_cast_fu_333_p1;
wire   [11:0] exp_fu_337_p2;
wire   [11:0] addr_V_fu_351_p2;
wire   [3:0] p_Result_i_i_fu_357_p4;
wire   [11:0] op2_assign_fu_386_p2;
wire  signed [31:0] op2_assign_i_cast_fu_392_p1;
wire   [77:0] r_V_fu_376_p4;
wire   [77:0] tmp_222_i_i_fu_396_p1;
wire   [255:0] tmp_199_i_i_fu_414_p1;
wire   [255:0] r_V_6_fu_417_p2;
wire   [78:0] prod_adj_V_fu_463_p4;
wire   [78:0] tmp_185_i_fu_473_p2;
wire   [77:0] tmp_134_i_fu_489_p4;
wire   [77:0] tmp_133_i_fu_479_p4;
wire   [78:0] tmp_s_fu_533_p1;
wire   [76:0] tmp_7_fu_559_p1;
wire   [76:0] tmp_8_fu_571_p1;
wire   [0:0] tmp_fu_554_p2;
wire   [77:0] r_V_8_fu_563_p3;
wire   [77:0] r_V_9_fu_575_p3;
wire   [15:0] p_Result_4_i_fu_609_p4;
wire   [15:0] p_Result_6_i_fu_627_p4;
wire   [31:0] p_Result_3_fu_619_p3;
wire   [31:0] p_Result_4_fu_637_p3;
wire   [15:0] p_Result_4_i1_fu_685_p4;
wire   [15:0] p_Result_6_i1_fu_703_p4;
wire   [31:0] p_Result_8_fu_695_p3;
wire   [31:0] p_Result_9_fu_713_p3;
wire   [2:0] tmp_23_fu_751_p2;
wire   [78:0] p_Val2_i_fu_782_p2;
wire   [78:0] p_Val2_23_fu_787_p3;
wire   [78:0] p_Val2_i3_fu_800_p2;
wire   [78:0] p_Val2_24_fu_805_p3;
wire   [0:0] tmp_43_fu_828_p3;
wire   [75:0] tmp_188_cast_fu_836_p1;
wire   [75:0] p_Val2_17_cast_fu_818_p4;
wire   [76:0] p_Val2_18_cast_fu_846_p1;
wire   [76:0] p_Val2_i9_fu_849_p2;
wire   [76:0] p_Val2_s_fu_855_p3;
wire  signed [78:0] p_Val2_cast_fu_862_p1;
wire   [31:0] p_Result_2_fu_872_p3;
wire   [31:0] p_Result_5_fu_879_p3;
reg   [31:0] c1_fu_886_p3;
wire   [77:0] tmp_i1_fu_902_p1;
wire   [31:0] shift_fu_917_p2;
wire   [31:0] shift_1_fu_927_p2;
wire   [0:0] tmp_203_i_fu_932_p2;
wire   [0:0] tmp5_fu_943_p2;
wire   [31:0] shift_2_fu_937_p2;
wire   [10:0] tmp_12_fu_955_p1;
wire   [10:0] tmp_15_fu_959_p1;
wire   [10:0] tmp_17_fu_963_p3;
wire   [10:0] tmp_18_fu_971_p1;
wire   [31:0] p_Result_7_fu_988_p3;
wire   [31:0] p_Result_10_fu_995_p3;
reg   [31:0] c1_1_fu_1002_p3;
wire   [77:0] tmp_i_fu_1018_p1;
wire   [31:0] shift_5_fu_1033_p2;
wire   [31:0] shift_6_fu_1043_p2;
wire   [0:0] tmp_203_i1_fu_1048_p2;
wire   [0:0] tmp15_fu_1059_p2;
wire   [31:0] shift_7_fu_1053_p2;
wire   [10:0] tmp_34_fu_1071_p1;
wire   [10:0] tmp_35_fu_1075_p1;
wire   [10:0] tmp_36_fu_1079_p3;
wire   [10:0] tmp_37_fu_1087_p1;
wire   [77:0] tmp_198_i_fu_1104_p1;
wire   [0:0] sel_tmp5_i_fu_1112_p2;
wire   [10:0] tmp_6_fu_1122_p2;
wire   [10:0] tmp_1_fu_1127_p3;
wire   [10:0] phitmp_i_fu_1134_p2;
wire   [77:0] tmp_198_i1_fu_1147_p1;
wire   [0:0] sel_tmp5_i1_fu_1155_p2;
wire   [10:0] tmp_13_fu_1165_p2;
wire   [10:0] tmp_14_fu_1170_p3;
wire   [10:0] phitmp_i1_fu_1177_p2;
wire   [77:0] tmp_201_i_fu_1190_p1;
wire   [77:0] tmp_202_i_fu_1193_p2;
wire   [77:0] tmp_204_i_fu_1198_p1;
wire   [77:0] tmp_205_i_fu_1201_p2;
wire   [51:0] tmp_22_fu_1216_p4;
wire   [51:0] tmp_31_fu_1226_p4;
wire   [51:0] tmp_32_fu_1236_p3;
wire   [51:0] tmp_10_fu_1243_p4;
wire   [51:0] tmp_2_fu_1207_p4;
wire   [51:0] tmp_11_fu_1252_p3;
wire   [77:0] tmp_201_i1_fu_1266_p1;
wire   [77:0] tmp_202_i1_fu_1269_p2;
wire   [77:0] tmp_204_i1_fu_1274_p1;
wire   [77:0] tmp_205_i1_fu_1277_p2;
wire   [51:0] tmp_39_fu_1292_p4;
wire   [51:0] tmp_40_fu_1302_p4;
wire   [51:0] tmp_41_fu_1312_p3;
wire   [51:0] tmp_20_fu_1319_p4;
wire   [51:0] tmp_16_fu_1283_p4;
wire   [51:0] tmp_21_fu_1328_p3;
wire   [0:0] ap_CS_fsm_state11;
wire   [63:0] p_Result_6_fu_1342_p4;
wire   [63:0] p_Result_11_fu_1354_p4;
wire   [63:0] tmp_246_neg_fu_1366_p2;
wire   [63:0] tmp_245_neg_fu_1376_p2;
wire   [0:0] sel_tmp_fu_1386_p2;
wire   [63:0] tmp_24_fu_1372_p1;
wire   [63:0] tmp_s_out_fu_1350_p1;
wire   [0:0] sel_tmp2_fu_1399_p2;
wire   [63:0] tmp_25_fu_1382_p1;
wire   [63:0] sel_tmp1_fu_1391_p3;
wire   [0:0] sel_tmp4_fu_1412_p2;
wire   [63:0] sel_tmp3_fu_1404_p3;
wire   [0:0] sel_tmp6_fu_1425_p2;
wire   [63:0] sel_tmp5_fu_1417_p3;
wire   [0:0] sel_tmp8_fu_1438_p2;
wire   [63:0] tmp_c_out_fu_1362_p1;
wire   [63:0] sel_tmp7_fu_1430_p3;
wire   [0:0] sel_tmp10_fu_1451_p2;
wire   [63:0] sel_tmp9_fu_1443_p3;
wire   [63:0] s_out_fu_1456_p3;
wire   [63:0] t_in_s_out_fu_1464_p3;
reg   [10:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'b1;
#0 ap_reg_grp_big_mult_v3_94_17_s_fu_296_ap_start = 1'b0;
#0 ap_reg_grp_big_mult_v3small_fu_301_ap_start = 1'b0;
end

sin_cos_range_redhbi #(
    .DataWidth( 256 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
hls_ref_4oPi_table_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_ref_4oPi_table_s_address0),
    .ce0(hls_ref_4oPi_table_s_ce0),
    .q0(hls_ref_4oPi_table_s_q0)
);

sin_cos_range_redibs #(
    .DataWidth( 126 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
hls_cordic_ctab_tab_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_cordic_ctab_tab_address0),
    .ce0(hls_cordic_ctab_tab_ce0),
    .q0(hls_cordic_ctab_tab_q0)
);

big_mult_v3_94_17_s grp_big_mult_v3_94_17_s_fu_296(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_big_mult_v3_94_17_s_fu_296_ap_start),
    .ap_done(grp_big_mult_v3_94_17_s_fu_296_ap_done),
    .ap_idle(grp_big_mult_v3_94_17_s_fu_296_ap_idle),
    .ap_ready(grp_big_mult_v3_94_17_s_fu_296_ap_ready),
    .a_V(h_fract_V_reg_1527),
    .ap_return(grp_big_mult_v3_94_17_s_fu_296_ap_return)
);

big_mult_v3small grp_big_mult_v3small_fu_301(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_big_mult_v3small_fu_301_ap_start),
    .ap_done(grp_big_mult_v3small_fu_301_ap_done),
    .ap_idle(grp_big_mult_v3small_fu_301_ap_idle),
    .ap_ready(grp_big_mult_v3small_fu_301_ap_ready),
    .a_V(ret_V_5_reg_1522),
    .b_V(r_V_5_reg_1517),
    .ap_return(grp_big_mult_v3small_fu_301_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_big_mult_v3_94_17_s_fu_296_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & ~(1'b0 == grp_big_mult_v3small_fu_301_ap_done))) begin
            ap_reg_grp_big_mult_v3_94_17_s_fu_296_ap_start <= 1'b1;
        end else if ((1'b1 == grp_big_mult_v3_94_17_s_fu_296_ap_ready)) begin
            ap_reg_grp_big_mult_v3_94_17_s_fu_296_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_big_mult_v3small_fu_301_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_reg_grp_big_mult_v3small_fu_301_ap_start <= 1'b1;
        end else if ((1'b1 == grp_big_mult_v3small_fu_301_ap_ready)) begin
            ap_reg_grp_big_mult_v3small_fu_301_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0) & ~(tmp_3_fu_343_p3 == 1'b0))) begin
        dout_V_reg_242 <= tmp_223_i_i_fu_400_p2;
    end else if (((1'b1 == ap_CS_fsm_state4) & (tmp_3_reg_1498 == 1'b0) & ~((tmp_3_reg_1498 == 1'b0) & (1'b0 == grp_big_mult_v3_94_17_s_fu_296_ap_done)))) begin
        dout_V_reg_242 <= tmp_135_i_fu_499_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0) & ~(tmp_3_fu_343_p3 == 1'b0))) begin
        k_V_reg_230 <= ap_const_lv3_0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (tmp_3_reg_1498 == 1'b0) & ~((tmp_3_reg_1498 == 1'b0) & (1'b0 == grp_big_mult_v3_94_17_s_fu_296_ap_done)))) begin
        k_V_reg_230 <= p_Val2_9_reg_1532;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_Val2_5_reg_273 <= tx_V_reg_1672;
    end else if (((1'b1 == ap_CS_fsm_state4) & ~((tmp_3_reg_1498 == 1'b0) & (1'b0 == grp_big_mult_v3_94_17_s_fu_296_ap_done)))) begin
        p_Val2_5_reg_273 <= ap_const_lv79_9B74EDA8435E5A67F5F;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_Val2_6_reg_261 <= ty_V_reg_1677;
    end else if (((1'b1 == ap_CS_fsm_state4) & ~((tmp_3_reg_1498 == 1'b0) & (1'b0 == grp_big_mult_v3_94_17_s_fu_296_ap_done)))) begin
        p_Val2_6_reg_261 <= ap_const_lv79_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_Val2_7_reg_251 <= tz_V_fu_866_p2;
    end else if (((1'b1 == ap_CS_fsm_state4) & ~((tmp_3_reg_1498 == 1'b0) & (1'b0 == grp_big_mult_v3_94_17_s_fu_296_ap_done)))) begin
        p_Val2_7_reg_251 <= loc_V_2_fu_517_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        sh_assign_reg_285 <= k_reg_1555;
    end else if (((1'b1 == ap_CS_fsm_state4) & ~((tmp_3_reg_1498 == 1'b0) & (1'b0 == grp_big_mult_v3_94_17_s_fu_296_ap_done)))) begin
        sh_assign_reg_285 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & ~(1'b0 == exitcond_i_fu_521_p2))) begin
        c2_1_reg_1628 <= c2_1_fu_731_p3;
        c2_reg_1599 <= c2_fu_655_p3;
        c3_1_reg_1635 <= c3_1_fu_739_p3;
        c3_reg_1606 <= c3_fu_663_p3;
        p_Result_8_i1_reg_1623 <= {{p_Val2_16_fu_591_p3[ap_const_lv32_1D : ap_const_lv32_E]}};
        p_Result_8_i_reg_1594 <= {{p_Val2_13_fu_583_p3[ap_const_lv32_1D : ap_const_lv32_E]}};
        p_Result_i1_reg_1589 <= {{p_Val2_13_fu_583_p3[ap_const_lv32_4D : ap_const_lv32_3E]}};
        p_Result_i2_reg_1618 <= {{p_Val2_16_fu_591_p3[ap_const_lv32_4D : ap_const_lv32_3E]}};
        p_Val2_13_reg_1577[77 : 1] <= p_Val2_13_fu_583_p3[77 : 1];
        p_Val2_16_reg_1583[77 : 1] <= p_Val2_16_fu_591_p3[77 : 1];
        sel_reg_1647 <= sel_fu_757_p3;
        tmp_26_reg_1657 <= tmp_26_fu_764_p2;
        tmp_27_reg_1662 <= tmp_27_fu_769_p2;
        tmp_33_reg_1642 <= tmp_33_fu_747_p1;
        tmp_9_reg_1613 <= tmp_9_fu_671_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (1'b0 == tmp_27_reg_1662) & (1'b0 == tmp_26_reg_1657))) begin
        c4_1_reg_1729 <= c4_1_fu_1010_p3;
        c4_reg_1692 <= c4_fu_894_p3;
        sel_tmp1_i1_reg_1751 <= sel_tmp1_i1_fu_1065_p2;
        sel_tmp1_i_reg_1714 <= sel_tmp1_i_fu_949_p2;
        tmp_197_i1_reg_1740 <= tmp_197_i1_fu_1027_p2;
        tmp_197_i_reg_1703 <= tmp_197_i_fu_911_p2;
        tmp_19_reg_1719 <= tmp_19_fu_975_p3;
        tmp_200_i1_reg_1746 <= tmp_200_i1_fu_1038_p2;
        tmp_200_i_reg_1709 <= tmp_200_i_fu_922_p2;
        tmp_206_i1_reg_1761 <= tmp_206_i1_fu_1099_p2;
        tmp_206_i_reg_1724 <= tmp_206_i_fu_983_p2;
        tmp_38_reg_1756 <= tmp_38_fu_1091_p3;
        tmp_i1_35_reg_1697 <= tmp_i1_35_fu_906_p2;
        tmp_i2_reg_1734 <= tmp_i2_fu_1022_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        d_V_reg_1667 <= p_Val2_7_reg_251[ap_const_lv32_4D];
        p_Val2_27_reg_1682 <= p_Val2_27_fu_840_p2;
        tx_V_reg_1672 <= tx_V_fu_794_p2;
        ty_V_reg_1677 <= ty_V_fu_812_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & ~(1'b0 == grp_big_mult_v3small_fu_301_ap_done))) begin
        h_fract_V_reg_1527 <= {{grp_big_mult_v3small_fu_301_ap_return[ap_const_lv32_79 : ap_const_lv32_2C]}};
        p_Val2_9_reg_1532 <= {{grp_big_mult_v3small_fu_301_ap_return[ap_const_lv32_7C : ap_const_lv32_7A]}};
        tmp_5_reg_1537 <= grp_big_mult_v3small_fu_301_ap_return[ap_const_lv32_7A];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        k_reg_1555 <= k_fu_527_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        loc_V_1_reg_1493 <= loc_V_1_fu_329_p1;
        loc_V_reg_1487 <= {{p_Val2_3_fu_307_p1[ap_const_lv32_3E : ap_const_lv32_34]}};
        p_Result_s_reg_1482 <= p_Val2_3_fu_307_p1[ap_const_lv32_3F];
        tmp_3_reg_1498 <= exp_fu_337_p2[ap_const_lv32_B];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_27_reg_1662) & (1'b0 == tmp_26_reg_1657) & (1'b1 == ap_CS_fsm_state10))) begin
        loc_V_3_reg_1798 <= loc_V_3_fu_1259_p3;
        loc_V_4_reg_1803 <= loc_V_4_fu_1335_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_27_reg_1662) & (1'b0 == tmp_26_reg_1657) & (1'b1 == ap_CS_fsm_state9))) begin
        out_exp_V_1_reg_1793 <= out_exp_V_1_fu_1183_p3;
        out_exp_V_reg_1777 <= out_exp_V_fu_1140_p3;
        sel_tmp6_i1_reg_1788 <= sel_tmp6_i1_fu_1160_p2;
        sel_tmp6_i_reg_1772 <= sel_tmp6_i_fu_1117_p2;
        tmp_199_i1_reg_1782 <= tmp_199_i1_fu_1150_p2;
        tmp_199_i_reg_1766 <= tmp_199_i_fu_1107_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_V_5_reg_1517[51 : 0] <= r_V_5_fu_406_p3[51 : 0];
        ret_V_5_reg_1522 <= {{r_V_6_fu_417_p2[ap_const_lv32_FF : ap_const_lv32_83]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & ~((tmp_3_reg_1498 == 1'b0) & (1'b0 == grp_big_mult_v3_94_17_s_fu_296_ap_done)))) begin
        r_V_7_reg_1542 <= {{dout_V_phi_fu_245_p4[ap_const_lv32_4D : ap_const_lv32_2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0) & (tmp_3_fu_343_p3 == 1'b0))) begin
        tmp_4_reg_1507 <= tmp_4_fu_372_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == exitcond_i_fu_521_p2))) begin
        x_s_V_reg_1566 <= x_s_V_fu_543_p2;
        y_s_V_reg_1560 <= y_s_V_fu_537_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1)) | (1'b1 == ap_CS_fsm_state11))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_3_reg_1498 == 1'b0))) begin
        dout_V_phi_fu_245_p4 = tmp_135_i_fu_499_p3;
    end else begin
        dout_V_phi_fu_245_p4 = dout_V_reg_242;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hls_cordic_ctab_tab_ce0 = 1'b1;
    end else begin
        hls_cordic_ctab_tab_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        hls_ref_4oPi_table_s_ce0 = 1'b1;
    end else begin
        hls_ref_4oPi_table_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~(ap_start == 1'b0) & ~(tmp_3_fu_343_p3 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~(ap_start == 1'b0) & (tmp_3_fu_343_p3 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (~(1'b0 == grp_big_mult_v3small_fu_301_ap_done)) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (~((tmp_3_reg_1498 == 1'b0) & (1'b0 == grp_big_mult_v3_94_17_s_fu_296_ap_done))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (~(1'b0 == exitcond_i_fu_521_p2)) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign addr_V_fu_351_p2 = ($signed(ap_const_lv12_C4D) + $signed(tmp_i_cast_fu_333_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state10 = ap_CS_fsm[ap_const_lv32_9];

assign ap_CS_fsm_state11 = ap_CS_fsm[ap_const_lv32_A];

assign ap_CS_fsm_state2 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_state3 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_state4 = ap_CS_fsm[ap_const_lv32_3];

assign ap_CS_fsm_state5 = ap_CS_fsm[ap_const_lv32_4];

assign ap_CS_fsm_state6 = ap_CS_fsm[ap_const_lv32_5];

assign ap_CS_fsm_state7 = ap_CS_fsm[ap_const_lv32_6];

assign ap_CS_fsm_state8 = ap_CS_fsm[ap_const_lv32_7];

assign ap_CS_fsm_state9 = ap_CS_fsm[ap_const_lv32_8];

assign ap_return = ((tmp_26_reg_1657[0:0] === 1'b1) ? ap_const_lv64_7FFFFFFFFFFFFFFF : t_in_s_out_fu_1464_p3);

always @ (p_Result_7_fu_988_p3) begin
    if (p_Result_7_fu_988_p3[31] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd0;
    end else if (p_Result_7_fu_988_p3[30] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd1;
    end else if (p_Result_7_fu_988_p3[29] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd2;
    end else if (p_Result_7_fu_988_p3[28] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd3;
    end else if (p_Result_7_fu_988_p3[27] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd4;
    end else if (p_Result_7_fu_988_p3[26] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd5;
    end else if (p_Result_7_fu_988_p3[25] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd6;
    end else if (p_Result_7_fu_988_p3[24] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd7;
    end else if (p_Result_7_fu_988_p3[23] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd8;
    end else if (p_Result_7_fu_988_p3[22] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd9;
    end else if (p_Result_7_fu_988_p3[21] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd10;
    end else if (p_Result_7_fu_988_p3[20] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd11;
    end else if (p_Result_7_fu_988_p3[19] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd12;
    end else if (p_Result_7_fu_988_p3[18] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd13;
    end else if (p_Result_7_fu_988_p3[17] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd14;
    end else if (p_Result_7_fu_988_p3[16] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd15;
    end else if (p_Result_7_fu_988_p3[15] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd16;
    end else if (p_Result_7_fu_988_p3[14] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd17;
    end else if (p_Result_7_fu_988_p3[13] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd18;
    end else if (p_Result_7_fu_988_p3[12] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd19;
    end else if (p_Result_7_fu_988_p3[11] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd20;
    end else if (p_Result_7_fu_988_p3[10] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd21;
    end else if (p_Result_7_fu_988_p3[9] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd22;
    end else if (p_Result_7_fu_988_p3[8] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd23;
    end else if (p_Result_7_fu_988_p3[7] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd24;
    end else if (p_Result_7_fu_988_p3[6] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd25;
    end else if (p_Result_7_fu_988_p3[5] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd26;
    end else if (p_Result_7_fu_988_p3[4] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd27;
    end else if (p_Result_7_fu_988_p3[3] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd28;
    end else if (p_Result_7_fu_988_p3[2] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd29;
    end else if (p_Result_7_fu_988_p3[1] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd30;
    end else if (p_Result_7_fu_988_p3[0] == 1'b1) begin
        c1_1_fu_1002_p3 = 32'd31;
    end else begin
        c1_1_fu_1002_p3 = 32'd32;
    end
end

always @ (p_Result_2_fu_872_p3) begin
    if (p_Result_2_fu_872_p3[31] == 1'b1) begin
        c1_fu_886_p3 = 32'd0;
    end else if (p_Result_2_fu_872_p3[30] == 1'b1) begin
        c1_fu_886_p3 = 32'd1;
    end else if (p_Result_2_fu_872_p3[29] == 1'b1) begin
        c1_fu_886_p3 = 32'd2;
    end else if (p_Result_2_fu_872_p3[28] == 1'b1) begin
        c1_fu_886_p3 = 32'd3;
    end else if (p_Result_2_fu_872_p3[27] == 1'b1) begin
        c1_fu_886_p3 = 32'd4;
    end else if (p_Result_2_fu_872_p3[26] == 1'b1) begin
        c1_fu_886_p3 = 32'd5;
    end else if (p_Result_2_fu_872_p3[25] == 1'b1) begin
        c1_fu_886_p3 = 32'd6;
    end else if (p_Result_2_fu_872_p3[24] == 1'b1) begin
        c1_fu_886_p3 = 32'd7;
    end else if (p_Result_2_fu_872_p3[23] == 1'b1) begin
        c1_fu_886_p3 = 32'd8;
    end else if (p_Result_2_fu_872_p3[22] == 1'b1) begin
        c1_fu_886_p3 = 32'd9;
    end else if (p_Result_2_fu_872_p3[21] == 1'b1) begin
        c1_fu_886_p3 = 32'd10;
    end else if (p_Result_2_fu_872_p3[20] == 1'b1) begin
        c1_fu_886_p3 = 32'd11;
    end else if (p_Result_2_fu_872_p3[19] == 1'b1) begin
        c1_fu_886_p3 = 32'd12;
    end else if (p_Result_2_fu_872_p3[18] == 1'b1) begin
        c1_fu_886_p3 = 32'd13;
    end else if (p_Result_2_fu_872_p3[17] == 1'b1) begin
        c1_fu_886_p3 = 32'd14;
    end else if (p_Result_2_fu_872_p3[16] == 1'b1) begin
        c1_fu_886_p3 = 32'd15;
    end else if (p_Result_2_fu_872_p3[15] == 1'b1) begin
        c1_fu_886_p3 = 32'd16;
    end else if (p_Result_2_fu_872_p3[14] == 1'b1) begin
        c1_fu_886_p3 = 32'd17;
    end else if (p_Result_2_fu_872_p3[13] == 1'b1) begin
        c1_fu_886_p3 = 32'd18;
    end else if (p_Result_2_fu_872_p3[12] == 1'b1) begin
        c1_fu_886_p3 = 32'd19;
    end else if (p_Result_2_fu_872_p3[11] == 1'b1) begin
        c1_fu_886_p3 = 32'd20;
    end else if (p_Result_2_fu_872_p3[10] == 1'b1) begin
        c1_fu_886_p3 = 32'd21;
    end else if (p_Result_2_fu_872_p3[9] == 1'b1) begin
        c1_fu_886_p3 = 32'd22;
    end else if (p_Result_2_fu_872_p3[8] == 1'b1) begin
        c1_fu_886_p3 = 32'd23;
    end else if (p_Result_2_fu_872_p3[7] == 1'b1) begin
        c1_fu_886_p3 = 32'd24;
    end else if (p_Result_2_fu_872_p3[6] == 1'b1) begin
        c1_fu_886_p3 = 32'd25;
    end else if (p_Result_2_fu_872_p3[5] == 1'b1) begin
        c1_fu_886_p3 = 32'd26;
    end else if (p_Result_2_fu_872_p3[4] == 1'b1) begin
        c1_fu_886_p3 = 32'd27;
    end else if (p_Result_2_fu_872_p3[3] == 1'b1) begin
        c1_fu_886_p3 = 32'd28;
    end else if (p_Result_2_fu_872_p3[2] == 1'b1) begin
        c1_fu_886_p3 = 32'd29;
    end else if (p_Result_2_fu_872_p3[1] == 1'b1) begin
        c1_fu_886_p3 = 32'd30;
    end else if (p_Result_2_fu_872_p3[0] == 1'b1) begin
        c1_fu_886_p3 = 32'd31;
    end else begin
        c1_fu_886_p3 = 32'd32;
    end
end

always @ (p_Result_8_fu_695_p3) begin
    if (p_Result_8_fu_695_p3[31] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd0;
    end else if (p_Result_8_fu_695_p3[30] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd1;
    end else if (p_Result_8_fu_695_p3[29] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd2;
    end else if (p_Result_8_fu_695_p3[28] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd3;
    end else if (p_Result_8_fu_695_p3[27] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd4;
    end else if (p_Result_8_fu_695_p3[26] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd5;
    end else if (p_Result_8_fu_695_p3[25] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd6;
    end else if (p_Result_8_fu_695_p3[24] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd7;
    end else if (p_Result_8_fu_695_p3[23] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd8;
    end else if (p_Result_8_fu_695_p3[22] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd9;
    end else if (p_Result_8_fu_695_p3[21] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd10;
    end else if (p_Result_8_fu_695_p3[20] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd11;
    end else if (p_Result_8_fu_695_p3[19] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd12;
    end else if (p_Result_8_fu_695_p3[18] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd13;
    end else if (p_Result_8_fu_695_p3[17] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd14;
    end else if (p_Result_8_fu_695_p3[16] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd15;
    end else if (p_Result_8_fu_695_p3[15] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd16;
    end else if (p_Result_8_fu_695_p3[14] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd17;
    end else if (p_Result_8_fu_695_p3[13] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd18;
    end else if (p_Result_8_fu_695_p3[12] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd19;
    end else if (p_Result_8_fu_695_p3[11] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd20;
    end else if (p_Result_8_fu_695_p3[10] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd21;
    end else if (p_Result_8_fu_695_p3[9] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd22;
    end else if (p_Result_8_fu_695_p3[8] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd23;
    end else if (p_Result_8_fu_695_p3[7] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd24;
    end else if (p_Result_8_fu_695_p3[6] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd25;
    end else if (p_Result_8_fu_695_p3[5] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd26;
    end else if (p_Result_8_fu_695_p3[4] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd27;
    end else if (p_Result_8_fu_695_p3[3] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd28;
    end else if (p_Result_8_fu_695_p3[2] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd29;
    end else if (p_Result_8_fu_695_p3[1] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd30;
    end else if (p_Result_8_fu_695_p3[0] == 1'b1) begin
        c2_1_fu_731_p3 = 32'd31;
    end else begin
        c2_1_fu_731_p3 = 32'd32;
    end
end

always @ (p_Result_3_fu_619_p3) begin
    if (p_Result_3_fu_619_p3[31] == 1'b1) begin
        c2_fu_655_p3 = 32'd0;
    end else if (p_Result_3_fu_619_p3[30] == 1'b1) begin
        c2_fu_655_p3 = 32'd1;
    end else if (p_Result_3_fu_619_p3[29] == 1'b1) begin
        c2_fu_655_p3 = 32'd2;
    end else if (p_Result_3_fu_619_p3[28] == 1'b1) begin
        c2_fu_655_p3 = 32'd3;
    end else if (p_Result_3_fu_619_p3[27] == 1'b1) begin
        c2_fu_655_p3 = 32'd4;
    end else if (p_Result_3_fu_619_p3[26] == 1'b1) begin
        c2_fu_655_p3 = 32'd5;
    end else if (p_Result_3_fu_619_p3[25] == 1'b1) begin
        c2_fu_655_p3 = 32'd6;
    end else if (p_Result_3_fu_619_p3[24] == 1'b1) begin
        c2_fu_655_p3 = 32'd7;
    end else if (p_Result_3_fu_619_p3[23] == 1'b1) begin
        c2_fu_655_p3 = 32'd8;
    end else if (p_Result_3_fu_619_p3[22] == 1'b1) begin
        c2_fu_655_p3 = 32'd9;
    end else if (p_Result_3_fu_619_p3[21] == 1'b1) begin
        c2_fu_655_p3 = 32'd10;
    end else if (p_Result_3_fu_619_p3[20] == 1'b1) begin
        c2_fu_655_p3 = 32'd11;
    end else if (p_Result_3_fu_619_p3[19] == 1'b1) begin
        c2_fu_655_p3 = 32'd12;
    end else if (p_Result_3_fu_619_p3[18] == 1'b1) begin
        c2_fu_655_p3 = 32'd13;
    end else if (p_Result_3_fu_619_p3[17] == 1'b1) begin
        c2_fu_655_p3 = 32'd14;
    end else if (p_Result_3_fu_619_p3[16] == 1'b1) begin
        c2_fu_655_p3 = 32'd15;
    end else if (p_Result_3_fu_619_p3[15] == 1'b1) begin
        c2_fu_655_p3 = 32'd16;
    end else if (p_Result_3_fu_619_p3[14] == 1'b1) begin
        c2_fu_655_p3 = 32'd17;
    end else if (p_Result_3_fu_619_p3[13] == 1'b1) begin
        c2_fu_655_p3 = 32'd18;
    end else if (p_Result_3_fu_619_p3[12] == 1'b1) begin
        c2_fu_655_p3 = 32'd19;
    end else if (p_Result_3_fu_619_p3[11] == 1'b1) begin
        c2_fu_655_p3 = 32'd20;
    end else if (p_Result_3_fu_619_p3[10] == 1'b1) begin
        c2_fu_655_p3 = 32'd21;
    end else if (p_Result_3_fu_619_p3[9] == 1'b1) begin
        c2_fu_655_p3 = 32'd22;
    end else if (p_Result_3_fu_619_p3[8] == 1'b1) begin
        c2_fu_655_p3 = 32'd23;
    end else if (p_Result_3_fu_619_p3[7] == 1'b1) begin
        c2_fu_655_p3 = 32'd24;
    end else if (p_Result_3_fu_619_p3[6] == 1'b1) begin
        c2_fu_655_p3 = 32'd25;
    end else if (p_Result_3_fu_619_p3[5] == 1'b1) begin
        c2_fu_655_p3 = 32'd26;
    end else if (p_Result_3_fu_619_p3[4] == 1'b1) begin
        c2_fu_655_p3 = 32'd27;
    end else if (p_Result_3_fu_619_p3[3] == 1'b1) begin
        c2_fu_655_p3 = 32'd28;
    end else if (p_Result_3_fu_619_p3[2] == 1'b1) begin
        c2_fu_655_p3 = 32'd29;
    end else if (p_Result_3_fu_619_p3[1] == 1'b1) begin
        c2_fu_655_p3 = 32'd30;
    end else if (p_Result_3_fu_619_p3[0] == 1'b1) begin
        c2_fu_655_p3 = 32'd31;
    end else begin
        c2_fu_655_p3 = 32'd32;
    end
end

always @ (p_Result_9_fu_713_p3) begin
    if (p_Result_9_fu_713_p3[31] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd0;
    end else if (p_Result_9_fu_713_p3[30] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd1;
    end else if (p_Result_9_fu_713_p3[29] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd2;
    end else if (p_Result_9_fu_713_p3[28] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd3;
    end else if (p_Result_9_fu_713_p3[27] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd4;
    end else if (p_Result_9_fu_713_p3[26] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd5;
    end else if (p_Result_9_fu_713_p3[25] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd6;
    end else if (p_Result_9_fu_713_p3[24] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd7;
    end else if (p_Result_9_fu_713_p3[23] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd8;
    end else if (p_Result_9_fu_713_p3[22] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd9;
    end else if (p_Result_9_fu_713_p3[21] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd10;
    end else if (p_Result_9_fu_713_p3[20] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd11;
    end else if (p_Result_9_fu_713_p3[19] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd12;
    end else if (p_Result_9_fu_713_p3[18] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd13;
    end else if (p_Result_9_fu_713_p3[17] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd14;
    end else if (p_Result_9_fu_713_p3[16] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd15;
    end else if (p_Result_9_fu_713_p3[15] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd16;
    end else if (p_Result_9_fu_713_p3[14] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd17;
    end else if (p_Result_9_fu_713_p3[13] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd18;
    end else if (p_Result_9_fu_713_p3[12] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd19;
    end else if (p_Result_9_fu_713_p3[11] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd20;
    end else if (p_Result_9_fu_713_p3[10] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd21;
    end else if (p_Result_9_fu_713_p3[9] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd22;
    end else if (p_Result_9_fu_713_p3[8] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd23;
    end else if (p_Result_9_fu_713_p3[7] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd24;
    end else if (p_Result_9_fu_713_p3[6] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd25;
    end else if (p_Result_9_fu_713_p3[5] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd26;
    end else if (p_Result_9_fu_713_p3[4] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd27;
    end else if (p_Result_9_fu_713_p3[3] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd28;
    end else if (p_Result_9_fu_713_p3[2] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd29;
    end else if (p_Result_9_fu_713_p3[1] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd30;
    end else if (p_Result_9_fu_713_p3[0] == 1'b1) begin
        c3_1_fu_739_p3 = 32'd31;
    end else begin
        c3_1_fu_739_p3 = 32'd32;
    end
end

always @ (p_Result_4_fu_637_p3) begin
    if (p_Result_4_fu_637_p3[31] == 1'b1) begin
        c3_fu_663_p3 = 32'd0;
    end else if (p_Result_4_fu_637_p3[30] == 1'b1) begin
        c3_fu_663_p3 = 32'd1;
    end else if (p_Result_4_fu_637_p3[29] == 1'b1) begin
        c3_fu_663_p3 = 32'd2;
    end else if (p_Result_4_fu_637_p3[28] == 1'b1) begin
        c3_fu_663_p3 = 32'd3;
    end else if (p_Result_4_fu_637_p3[27] == 1'b1) begin
        c3_fu_663_p3 = 32'd4;
    end else if (p_Result_4_fu_637_p3[26] == 1'b1) begin
        c3_fu_663_p3 = 32'd5;
    end else if (p_Result_4_fu_637_p3[25] == 1'b1) begin
        c3_fu_663_p3 = 32'd6;
    end else if (p_Result_4_fu_637_p3[24] == 1'b1) begin
        c3_fu_663_p3 = 32'd7;
    end else if (p_Result_4_fu_637_p3[23] == 1'b1) begin
        c3_fu_663_p3 = 32'd8;
    end else if (p_Result_4_fu_637_p3[22] == 1'b1) begin
        c3_fu_663_p3 = 32'd9;
    end else if (p_Result_4_fu_637_p3[21] == 1'b1) begin
        c3_fu_663_p3 = 32'd10;
    end else if (p_Result_4_fu_637_p3[20] == 1'b1) begin
        c3_fu_663_p3 = 32'd11;
    end else if (p_Result_4_fu_637_p3[19] == 1'b1) begin
        c3_fu_663_p3 = 32'd12;
    end else if (p_Result_4_fu_637_p3[18] == 1'b1) begin
        c3_fu_663_p3 = 32'd13;
    end else if (p_Result_4_fu_637_p3[17] == 1'b1) begin
        c3_fu_663_p3 = 32'd14;
    end else if (p_Result_4_fu_637_p3[16] == 1'b1) begin
        c3_fu_663_p3 = 32'd15;
    end else if (p_Result_4_fu_637_p3[15] == 1'b1) begin
        c3_fu_663_p3 = 32'd16;
    end else if (p_Result_4_fu_637_p3[14] == 1'b1) begin
        c3_fu_663_p3 = 32'd17;
    end else if (p_Result_4_fu_637_p3[13] == 1'b1) begin
        c3_fu_663_p3 = 32'd18;
    end else if (p_Result_4_fu_637_p3[12] == 1'b1) begin
        c3_fu_663_p3 = 32'd19;
    end else if (p_Result_4_fu_637_p3[11] == 1'b1) begin
        c3_fu_663_p3 = 32'd20;
    end else if (p_Result_4_fu_637_p3[10] == 1'b1) begin
        c3_fu_663_p3 = 32'd21;
    end else if (p_Result_4_fu_637_p3[9] == 1'b1) begin
        c3_fu_663_p3 = 32'd22;
    end else if (p_Result_4_fu_637_p3[8] == 1'b1) begin
        c3_fu_663_p3 = 32'd23;
    end else if (p_Result_4_fu_637_p3[7] == 1'b1) begin
        c3_fu_663_p3 = 32'd24;
    end else if (p_Result_4_fu_637_p3[6] == 1'b1) begin
        c3_fu_663_p3 = 32'd25;
    end else if (p_Result_4_fu_637_p3[5] == 1'b1) begin
        c3_fu_663_p3 = 32'd26;
    end else if (p_Result_4_fu_637_p3[4] == 1'b1) begin
        c3_fu_663_p3 = 32'd27;
    end else if (p_Result_4_fu_637_p3[3] == 1'b1) begin
        c3_fu_663_p3 = 32'd28;
    end else if (p_Result_4_fu_637_p3[2] == 1'b1) begin
        c3_fu_663_p3 = 32'd29;
    end else if (p_Result_4_fu_637_p3[1] == 1'b1) begin
        c3_fu_663_p3 = 32'd30;
    end else if (p_Result_4_fu_637_p3[0] == 1'b1) begin
        c3_fu_663_p3 = 32'd31;
    end else begin
        c3_fu_663_p3 = 32'd32;
    end
end

always @ (p_Result_10_fu_995_p3) begin
    if (p_Result_10_fu_995_p3[31] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd0;
    end else if (p_Result_10_fu_995_p3[30] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd1;
    end else if (p_Result_10_fu_995_p3[29] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd2;
    end else if (p_Result_10_fu_995_p3[28] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd3;
    end else if (p_Result_10_fu_995_p3[27] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd4;
    end else if (p_Result_10_fu_995_p3[26] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd5;
    end else if (p_Result_10_fu_995_p3[25] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd6;
    end else if (p_Result_10_fu_995_p3[24] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd7;
    end else if (p_Result_10_fu_995_p3[23] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd8;
    end else if (p_Result_10_fu_995_p3[22] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd9;
    end else if (p_Result_10_fu_995_p3[21] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd10;
    end else if (p_Result_10_fu_995_p3[20] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd11;
    end else if (p_Result_10_fu_995_p3[19] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd12;
    end else if (p_Result_10_fu_995_p3[18] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd13;
    end else if (p_Result_10_fu_995_p3[17] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd14;
    end else if (p_Result_10_fu_995_p3[16] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd15;
    end else if (p_Result_10_fu_995_p3[15] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd16;
    end else if (p_Result_10_fu_995_p3[14] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd17;
    end else if (p_Result_10_fu_995_p3[13] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd18;
    end else if (p_Result_10_fu_995_p3[12] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd19;
    end else if (p_Result_10_fu_995_p3[11] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd20;
    end else if (p_Result_10_fu_995_p3[10] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd21;
    end else if (p_Result_10_fu_995_p3[9] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd22;
    end else if (p_Result_10_fu_995_p3[8] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd23;
    end else if (p_Result_10_fu_995_p3[7] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd24;
    end else if (p_Result_10_fu_995_p3[6] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd25;
    end else if (p_Result_10_fu_995_p3[5] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd26;
    end else if (p_Result_10_fu_995_p3[4] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd27;
    end else if (p_Result_10_fu_995_p3[3] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd28;
    end else if (p_Result_10_fu_995_p3[2] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd29;
    end else if (p_Result_10_fu_995_p3[1] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd30;
    end else if (p_Result_10_fu_995_p3[0] == 1'b1) begin
        c4_1_fu_1010_p3 = 32'd31;
    end else begin
        c4_1_fu_1010_p3 = 32'd32;
    end
end

always @ (p_Result_5_fu_879_p3) begin
    if (p_Result_5_fu_879_p3[31] == 1'b1) begin
        c4_fu_894_p3 = 32'd0;
    end else if (p_Result_5_fu_879_p3[30] == 1'b1) begin
        c4_fu_894_p3 = 32'd1;
    end else if (p_Result_5_fu_879_p3[29] == 1'b1) begin
        c4_fu_894_p3 = 32'd2;
    end else if (p_Result_5_fu_879_p3[28] == 1'b1) begin
        c4_fu_894_p3 = 32'd3;
    end else if (p_Result_5_fu_879_p3[27] == 1'b1) begin
        c4_fu_894_p3 = 32'd4;
    end else if (p_Result_5_fu_879_p3[26] == 1'b1) begin
        c4_fu_894_p3 = 32'd5;
    end else if (p_Result_5_fu_879_p3[25] == 1'b1) begin
        c4_fu_894_p3 = 32'd6;
    end else if (p_Result_5_fu_879_p3[24] == 1'b1) begin
        c4_fu_894_p3 = 32'd7;
    end else if (p_Result_5_fu_879_p3[23] == 1'b1) begin
        c4_fu_894_p3 = 32'd8;
    end else if (p_Result_5_fu_879_p3[22] == 1'b1) begin
        c4_fu_894_p3 = 32'd9;
    end else if (p_Result_5_fu_879_p3[21] == 1'b1) begin
        c4_fu_894_p3 = 32'd10;
    end else if (p_Result_5_fu_879_p3[20] == 1'b1) begin
        c4_fu_894_p3 = 32'd11;
    end else if (p_Result_5_fu_879_p3[19] == 1'b1) begin
        c4_fu_894_p3 = 32'd12;
    end else if (p_Result_5_fu_879_p3[18] == 1'b1) begin
        c4_fu_894_p3 = 32'd13;
    end else if (p_Result_5_fu_879_p3[17] == 1'b1) begin
        c4_fu_894_p3 = 32'd14;
    end else if (p_Result_5_fu_879_p3[16] == 1'b1) begin
        c4_fu_894_p3 = 32'd15;
    end else if (p_Result_5_fu_879_p3[15] == 1'b1) begin
        c4_fu_894_p3 = 32'd16;
    end else if (p_Result_5_fu_879_p3[14] == 1'b1) begin
        c4_fu_894_p3 = 32'd17;
    end else if (p_Result_5_fu_879_p3[13] == 1'b1) begin
        c4_fu_894_p3 = 32'd18;
    end else if (p_Result_5_fu_879_p3[12] == 1'b1) begin
        c4_fu_894_p3 = 32'd19;
    end else if (p_Result_5_fu_879_p3[11] == 1'b1) begin
        c4_fu_894_p3 = 32'd20;
    end else if (p_Result_5_fu_879_p3[10] == 1'b1) begin
        c4_fu_894_p3 = 32'd21;
    end else if (p_Result_5_fu_879_p3[9] == 1'b1) begin
        c4_fu_894_p3 = 32'd22;
    end else if (p_Result_5_fu_879_p3[8] == 1'b1) begin
        c4_fu_894_p3 = 32'd23;
    end else if (p_Result_5_fu_879_p3[7] == 1'b1) begin
        c4_fu_894_p3 = 32'd24;
    end else if (p_Result_5_fu_879_p3[6] == 1'b1) begin
        c4_fu_894_p3 = 32'd25;
    end else if (p_Result_5_fu_879_p3[5] == 1'b1) begin
        c4_fu_894_p3 = 32'd26;
    end else if (p_Result_5_fu_879_p3[4] == 1'b1) begin
        c4_fu_894_p3 = 32'd27;
    end else if (p_Result_5_fu_879_p3[3] == 1'b1) begin
        c4_fu_894_p3 = 32'd28;
    end else if (p_Result_5_fu_879_p3[2] == 1'b1) begin
        c4_fu_894_p3 = 32'd29;
    end else if (p_Result_5_fu_879_p3[1] == 1'b1) begin
        c4_fu_894_p3 = 32'd30;
    end else if (p_Result_5_fu_879_p3[0] == 1'b1) begin
        c4_fu_894_p3 = 32'd31;
    end else begin
        c4_fu_894_p3 = 32'd32;
    end
end

assign d_V_fu_774_p3 = p_Val2_7_reg_251[ap_const_lv32_4D];

assign exitcond_i_fu_521_p2 = ((sh_assign_reg_285 == ap_const_lv7_4E) ? 1'b1 : 1'b0);

assign exp_fu_337_p2 = ($signed(ap_const_lv12_C01) + $signed(tmp_i_cast_fu_333_p1));

assign grp_big_mult_v3_94_17_s_fu_296_ap_start = ap_reg_grp_big_mult_v3_94_17_s_fu_296_ap_start;

assign grp_big_mult_v3small_fu_301_ap_start = ap_reg_grp_big_mult_v3small_fu_301_ap_start;

assign hls_cordic_ctab_tab_address0 = tmp_28_fu_549_p1;

assign hls_ref_4oPi_table_s_address0 = tmp_i_i_fu_367_p1;

assign k_fu_527_p2 = (sh_assign_reg_285 + ap_const_lv7_1);

assign loc_V_1_fu_329_p1 = p_Val2_3_fu_307_p1[51:0];

assign loc_V_2_fu_517_p1 = r_V_7_fu_507_p4;

assign loc_V_3_fu_1259_p3 = ((sel_tmp6_i_reg_1772[0:0] === 1'b1) ? tmp_2_fu_1207_p4 : tmp_11_fu_1252_p3);

assign loc_V_4_fu_1335_p3 = ((sel_tmp6_i1_reg_1788[0:0] === 1'b1) ? tmp_16_fu_1283_p4 : tmp_21_fu_1328_p3);

assign loc_V_fu_319_p4 = {{p_Val2_3_fu_307_p1[ap_const_lv32_3E : ap_const_lv32_34]}};

assign op2_assign_fu_386_p2 = (ap_const_lv12_3FE - tmp_i_cast_fu_333_p1);

assign op2_assign_i_cast_fu_392_p1 = $signed(op2_assign_fu_386_p2);

assign out_exp_V_1_fu_1183_p3 = ((tmp_206_i1_reg_1761[0:0] === 1'b1) ? ap_const_lv11_0 : phitmp_i1_fu_1177_p2);

assign out_exp_V_fu_1140_p3 = ((tmp_206_i_reg_1724[0:0] === 1'b1) ? ap_const_lv11_0 : phitmp_i_fu_1134_p2);

assign p_Result_10_fu_995_p3 = {{p_Result_8_i1_reg_1623}, {ap_const_lv16_8000}};

assign p_Result_11_fu_1354_p4 = {{{{1'b0}, {out_exp_V_1_reg_1793}}}, {loc_V_4_reg_1803}};

assign p_Result_2_fu_872_p3 = {{p_Result_i1_reg_1589}, {ap_const_lv16_8000}};

assign p_Result_3_fu_619_p3 = {{p_Result_4_i_fu_609_p4}, {ap_const_lv16_8000}};

assign p_Result_4_fu_637_p3 = {{p_Result_6_i_fu_627_p4}, {ap_const_lv16_8000}};

assign p_Result_4_i1_fu_685_p4 = {{p_Val2_16_fu_591_p3[ap_const_lv32_3D : ap_const_lv32_2E]}};

assign p_Result_4_i_fu_609_p4 = {{p_Val2_13_fu_583_p3[ap_const_lv32_3D : ap_const_lv32_2E]}};

assign p_Result_5_fu_879_p3 = {{p_Result_8_i_reg_1594}, {ap_const_lv16_8000}};

assign p_Result_6_fu_1342_p4 = {{{{1'b0}, {out_exp_V_reg_1777}}}, {loc_V_3_reg_1798}};

assign p_Result_6_i1_fu_703_p4 = {{p_Val2_16_fu_591_p3[ap_const_lv32_2D : ap_const_lv32_1E]}};

assign p_Result_6_i_fu_627_p4 = {{p_Val2_13_fu_583_p3[ap_const_lv32_2D : ap_const_lv32_1E]}};

assign p_Result_7_fu_988_p3 = {{p_Result_i2_reg_1618}, {ap_const_lv16_8000}};

assign p_Result_8_fu_695_p3 = {{p_Result_4_i1_fu_685_p4}, {ap_const_lv16_8000}};

assign p_Result_9_fu_713_p3 = {{p_Result_6_i1_fu_703_p4}, {ap_const_lv16_8000}};

assign p_Result_i_i_fu_357_p4 = {{addr_V_fu_351_p2[ap_const_lv32_A : ap_const_lv32_7]}};

assign p_Val2_13_fu_583_p3 = ((tmp_fu_554_p2[0:0] === 1'b1) ? ap_const_lv78_0 : r_V_8_fu_563_p3);

assign p_Val2_16_fu_591_p3 = ((tmp_fu_554_p2[0:0] === 1'b1) ? ap_const_lv78_20000000000000000000 : r_V_9_fu_575_p3);

assign p_Val2_17_cast_fu_818_p4 = {{hls_cordic_ctab_tab_q0[ap_const_lv32_7D : ap_const_lv32_32]}};

assign p_Val2_18_cast_fu_846_p1 = p_Val2_27_reg_1682;

assign p_Val2_23_fu_787_p3 = ((d_V_fu_774_p3[0:0] === 1'b1) ? y_s_V_reg_1560 : p_Val2_i_fu_782_p2);

assign p_Val2_24_fu_805_p3 = ((d_V_fu_774_p3[0:0] === 1'b1) ? p_Val2_i3_fu_800_p2 : x_s_V_reg_1566);

assign p_Val2_27_fu_840_p2 = (tmp_188_cast_fu_836_p1 + p_Val2_17_cast_fu_818_p4);

assign p_Val2_3_fu_307_p1 = t_in;

assign p_Val2_cast_fu_862_p1 = $signed(p_Val2_s_fu_855_p3);

assign p_Val2_i3_fu_800_p2 = (ap_const_lv79_0 - x_s_V_reg_1566);

assign p_Val2_i9_fu_849_p2 = (ap_const_lv77_0 - p_Val2_18_cast_fu_846_p1);

assign p_Val2_i_fu_782_p2 = (ap_const_lv79_0 - y_s_V_reg_1560);

assign p_Val2_s_fu_855_p3 = ((d_V_reg_1667[0:0] === 1'b1) ? p_Val2_18_cast_fu_846_p1 : p_Val2_i9_fu_849_p2);

assign phitmp_i1_fu_1177_p2 = (ap_const_lv11_3FF - tmp_14_fu_1170_p3);

assign phitmp_i_fu_1134_p2 = (ap_const_lv11_3FF - tmp_1_fu_1127_p3);

assign prod_adj_V_fu_463_p4 = {{grp_big_mult_v3_94_17_s_fu_296_ap_return[ap_const_lv32_9B : ap_const_lv32_4D]}};

assign r_V_5_fu_406_p3 = {{1'b1}, {loc_V_1_reg_1493}};

assign r_V_6_fu_417_p2 = hls_ref_4oPi_table_s_q0 << tmp_199_i_i_fu_414_p1;

assign r_V_7_fu_507_p4 = {{dout_V_phi_fu_245_p4[ap_const_lv32_4D : ap_const_lv32_2]}};

assign r_V_8_fu_563_p3 = {{tmp_7_fu_559_p1}, {1'b0}};

assign r_V_9_fu_575_p3 = {{tmp_8_fu_571_p1}, {1'b0}};

assign r_V_fu_376_p4 = {{{{1'b1}, {loc_V_1_fu_329_p1}}}, {ap_const_lv25_0}};

assign s_out_fu_1456_p3 = ((sel_tmp10_fu_1451_p2[0:0] === 1'b1) ? tmp_c_out_fu_1362_p1 : sel_tmp9_fu_1443_p3);

assign sel_fu_757_p3 = ((p_Result_s_reg_1482[0:0] === 1'b1) ? tmp_23_fu_751_p2 : k_V_reg_230);

assign sel_tmp10_fu_1451_p2 = ((sel_reg_1647 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp1_fu_1391_p3 = ((sel_tmp_fu_1386_p2[0:0] === 1'b1) ? tmp_24_fu_1372_p1 : tmp_s_out_fu_1350_p1);

assign sel_tmp1_i1_fu_1065_p2 = (tmp15_fu_1059_p2 & tmp_197_i1_fu_1027_p2);

assign sel_tmp1_i_fu_949_p2 = (tmp5_fu_943_p2 & tmp_197_i_fu_911_p2);

assign sel_tmp2_fu_1399_p2 = ((sel_reg_1647 == ap_const_lv3_6) ? 1'b1 : 1'b0);

assign sel_tmp3_fu_1404_p3 = ((sel_tmp2_fu_1399_p2[0:0] === 1'b1) ? tmp_25_fu_1382_p1 : sel_tmp1_fu_1391_p3);

assign sel_tmp4_fu_1412_p2 = ((sel_reg_1647 == ap_const_lv3_5) ? 1'b1 : 1'b0);

assign sel_tmp5_fu_1417_p3 = ((sel_tmp4_fu_1412_p2[0:0] === 1'b1) ? tmp_25_fu_1382_p1 : sel_tmp3_fu_1404_p3);

assign sel_tmp5_i1_fu_1155_p2 = (tmp_200_i1_reg_1746 ^ 1'b1);

assign sel_tmp5_i_fu_1112_p2 = (tmp_200_i_reg_1709 ^ 1'b1);

assign sel_tmp6_fu_1425_p2 = ((sel_reg_1647 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp6_i1_fu_1160_p2 = (tmp_197_i1_reg_1740 & sel_tmp5_i1_fu_1155_p2);

assign sel_tmp6_i_fu_1117_p2 = (tmp_197_i_reg_1703 & sel_tmp5_i_fu_1112_p2);

assign sel_tmp7_fu_1430_p3 = ((sel_tmp6_fu_1425_p2[0:0] === 1'b1) ? tmp_24_fu_1372_p1 : sel_tmp5_fu_1417_p3);

assign sel_tmp8_fu_1438_p2 = ((sel_reg_1647 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp9_fu_1443_p3 = ((sel_tmp8_fu_1438_p2[0:0] === 1'b1) ? tmp_c_out_fu_1362_p1 : sel_tmp7_fu_1430_p3);

assign sel_tmp_fu_1386_p2 = ((sel_reg_1647 == ap_const_lv3_7) ? 1'b1 : 1'b0);

assign shift_1_fu_927_p2 = (c3_reg_1606 + shift_fu_917_p2);

assign shift_2_fu_937_p2 = (c4_fu_894_p3 + shift_1_fu_927_p2);

assign shift_5_fu_1033_p2 = (c2_1_reg_1628 + ap_const_lv32_10);

assign shift_6_fu_1043_p2 = (c3_1_reg_1635 + shift_5_fu_1033_p2);

assign shift_7_fu_1053_p2 = (c4_1_fu_1010_p3 + shift_6_fu_1043_p2);

assign shift_fu_917_p2 = (c2_reg_1599 + ap_const_lv32_10);

assign t_in_s_out_fu_1464_p3 = ((tmp_27_reg_1662[0:0] === 1'b1) ? t_in : s_out_fu_1456_p3);

assign tmp15_fu_1059_p2 = (tmp_200_i1_fu_1038_p2 & tmp_203_i1_fu_1048_p2);

assign tmp5_fu_943_p2 = (tmp_200_i_fu_922_p2 & tmp_203_i_fu_932_p2);

assign tmp_10_fu_1243_p4 = {{tmp_i1_35_reg_1697[ap_const_lv32_4C : ap_const_lv32_19]}};

assign tmp_11_fu_1252_p3 = ((tmp_197_i_reg_1703[0:0] === 1'b1) ? tmp_32_fu_1236_p3 : tmp_10_fu_1243_p4);

assign tmp_12_fu_955_p1 = shift_2_fu_937_p2[10:0];

assign tmp_133_i_fu_479_p4 = {{grp_big_mult_v3_94_17_s_fu_296_ap_return[ap_const_lv32_9B : ap_const_lv32_4E]}};

assign tmp_134_i_fu_489_p4 = {{tmp_185_i_fu_473_p2[ap_const_lv32_4E : ap_const_lv32_1]}};

assign tmp_135_i_fu_499_p3 = ((tmp_5_reg_1537[0:0] === 1'b1) ? tmp_134_i_fu_489_p4 : tmp_133_i_fu_479_p4);

assign tmp_13_fu_1165_p2 = (tmp_33_reg_1642 + ap_const_lv11_10);

assign tmp_14_fu_1170_p3 = ((sel_tmp6_i1_fu_1160_p2[0:0] === 1'b1) ? tmp_13_fu_1165_p2 : tmp_38_reg_1756);

assign tmp_15_fu_959_p1 = shift_1_fu_927_p2[10:0];

assign tmp_16_fu_1283_p4 = {{tmp_199_i1_reg_1782[ap_const_lv32_4C : ap_const_lv32_19]}};

assign tmp_17_fu_963_p3 = ((sel_tmp1_i_fu_949_p2[0:0] === 1'b1) ? tmp_12_fu_955_p1 : tmp_15_fu_959_p1);

assign tmp_185_i_fu_473_p2 = ($signed(ap_const_lv79_6487ED5110B4611A6263) - $signed(prod_adj_V_fu_463_p4));

assign tmp_188_cast_fu_836_p1 = tmp_43_fu_828_p3;

assign tmp_18_fu_971_p1 = c1_fu_886_p3[10:0];

assign tmp_197_i1_fu_1027_p2 = ((c1_1_fu_1002_p3 == ap_const_lv32_10) ? 1'b1 : 1'b0);

assign tmp_197_i_fu_911_p2 = ((c1_fu_886_p3 == ap_const_lv32_10) ? 1'b1 : 1'b0);

assign tmp_198_i1_fu_1147_p1 = c2_1_reg_1628;

assign tmp_198_i_fu_1104_p1 = c2_reg_1599;

assign tmp_199_i1_fu_1150_p2 = tmp_i2_reg_1734 << tmp_198_i1_fu_1147_p1;

assign tmp_199_i_fu_1107_p2 = tmp_i1_35_reg_1697 << tmp_198_i_fu_1104_p1;

assign tmp_199_i_i_fu_414_p1 = tmp_4_reg_1507;

assign tmp_19_fu_975_p3 = ((tmp_197_i_fu_911_p2[0:0] === 1'b1) ? tmp_17_fu_963_p3 : tmp_18_fu_971_p1);

assign tmp_1_fu_1127_p3 = ((sel_tmp6_i_fu_1117_p2[0:0] === 1'b1) ? tmp_6_fu_1122_p2 : tmp_19_reg_1719);

assign tmp_200_i1_fu_1038_p2 = ((c2_1_reg_1628 == ap_const_lv32_10) ? 1'b1 : 1'b0);

assign tmp_200_i_fu_922_p2 = ((c2_reg_1599 == ap_const_lv32_10) ? 1'b1 : 1'b0);

assign tmp_201_i1_fu_1266_p1 = c3_1_reg_1635;

assign tmp_201_i_fu_1190_p1 = c3_reg_1606;

assign tmp_202_i1_fu_1269_p2 = tmp_199_i1_reg_1782 << tmp_201_i1_fu_1266_p1;

assign tmp_202_i_fu_1193_p2 = tmp_199_i_reg_1766 << tmp_201_i_fu_1190_p1;

assign tmp_203_i1_fu_1048_p2 = ((c3_1_reg_1635 == ap_const_lv32_10) ? 1'b1 : 1'b0);

assign tmp_203_i_fu_932_p2 = ((c3_reg_1606 == ap_const_lv32_10) ? 1'b1 : 1'b0);

assign tmp_204_i1_fu_1274_p1 = c4_1_reg_1729;

assign tmp_204_i_fu_1198_p1 = c4_reg_1692;

assign tmp_205_i1_fu_1277_p2 = tmp_202_i1_fu_1269_p2 << tmp_204_i1_fu_1274_p1;

assign tmp_205_i_fu_1201_p2 = tmp_202_i_fu_1193_p2 << tmp_204_i_fu_1198_p1;

assign tmp_206_i1_fu_1099_p2 = ((p_Val2_16_reg_1583 == ap_const_lv78_0) ? 1'b1 : 1'b0);

assign tmp_206_i_fu_983_p2 = ((p_Val2_13_reg_1577 == ap_const_lv78_0) ? 1'b1 : 1'b0);

assign tmp_20_fu_1319_p4 = {{tmp_i2_reg_1734[ap_const_lv32_4C : ap_const_lv32_19]}};

assign tmp_21_fu_1328_p3 = ((tmp_197_i1_reg_1740[0:0] === 1'b1) ? tmp_41_fu_1312_p3 : tmp_20_fu_1319_p4);

assign tmp_222_i_i_fu_396_p1 = $unsigned(op2_assign_i_cast_fu_392_p1);

assign tmp_223_i_i_fu_400_p2 = r_V_fu_376_p4 >> tmp_222_i_i_fu_396_p1;

assign tmp_22_fu_1216_p4 = {{tmp_205_i_fu_1201_p2[ap_const_lv32_4C : ap_const_lv32_19]}};

assign tmp_23_fu_751_p2 = (k_V_reg_230 ^ ap_const_lv3_7);

assign tmp_245_neg_fu_1376_p2 = (p_Result_11_fu_1354_p4 ^ ap_const_lv64_8000000000000000);

assign tmp_246_neg_fu_1366_p2 = (p_Result_6_fu_1342_p4 ^ ap_const_lv64_8000000000000000);

assign tmp_24_fu_1372_p1 = tmp_246_neg_fu_1366_p2;

assign tmp_25_fu_1382_p1 = tmp_245_neg_fu_1376_p2;

assign tmp_26_fu_764_p2 = ((loc_V_reg_1487 == ap_const_lv11_7FF) ? 1'b1 : 1'b0);

assign tmp_27_fu_769_p2 = ((loc_V_reg_1487 < ap_const_lv11_3E7) ? 1'b1 : 1'b0);

assign tmp_28_fu_549_p1 = sh_assign_reg_285;

assign tmp_2_fu_1207_p4 = {{tmp_199_i_reg_1766[ap_const_lv32_4C : ap_const_lv32_19]}};

assign tmp_31_fu_1226_p4 = {{tmp_202_i_fu_1193_p2[ap_const_lv32_4C : ap_const_lv32_19]}};

assign tmp_32_fu_1236_p3 = ((sel_tmp1_i_reg_1714[0:0] === 1'b1) ? tmp_22_fu_1216_p4 : tmp_31_fu_1226_p4);

assign tmp_33_fu_747_p1 = c2_1_fu_731_p3[10:0];

assign tmp_34_fu_1071_p1 = shift_7_fu_1053_p2[10:0];

assign tmp_35_fu_1075_p1 = shift_6_fu_1043_p2[10:0];

assign tmp_36_fu_1079_p3 = ((sel_tmp1_i1_fu_1065_p2[0:0] === 1'b1) ? tmp_34_fu_1071_p1 : tmp_35_fu_1075_p1);

assign tmp_37_fu_1087_p1 = c1_1_fu_1002_p3[10:0];

assign tmp_38_fu_1091_p3 = ((tmp_197_i1_fu_1027_p2[0:0] === 1'b1) ? tmp_36_fu_1079_p3 : tmp_37_fu_1087_p1);

assign tmp_39_fu_1292_p4 = {{tmp_205_i1_fu_1277_p2[ap_const_lv32_4C : ap_const_lv32_19]}};

assign tmp_3_fu_343_p3 = exp_fu_337_p2[ap_const_lv32_B];

assign tmp_40_fu_1302_p4 = {{tmp_202_i1_fu_1269_p2[ap_const_lv32_4C : ap_const_lv32_19]}};

assign tmp_41_fu_1312_p3 = ((sel_tmp1_i1_reg_1751[0:0] === 1'b1) ? tmp_39_fu_1292_p4 : tmp_40_fu_1302_p4);

assign tmp_43_fu_828_p3 = hls_cordic_ctab_tab_q0[ap_const_lv32_31];

assign tmp_4_fu_372_p1 = addr_V_fu_351_p2[6:0];

assign tmp_6_fu_1122_p2 = (tmp_9_reg_1613 + ap_const_lv11_10);

assign tmp_7_fu_559_p1 = p_Val2_6_reg_261[76:0];

assign tmp_8_fu_571_p1 = p_Val2_5_reg_273[76:0];

assign tmp_9_fu_671_p1 = c2_fu_655_p3[10:0];

assign tmp_c_out_fu_1362_p1 = p_Result_11_fu_1354_p4;

assign tmp_fu_554_p2 = ((r_V_7_reg_1542 == ap_const_lv76_0) ? 1'b1 : 1'b0);

assign tmp_i1_35_fu_906_p2 = p_Val2_13_reg_1577 << tmp_i1_fu_902_p1;

assign tmp_i1_fu_902_p1 = c1_fu_886_p3;

assign tmp_i2_fu_1022_p2 = p_Val2_16_reg_1583 << tmp_i_fu_1018_p1;

assign tmp_i_cast_fu_333_p1 = loc_V_fu_319_p4;

assign tmp_i_fu_1018_p1 = c1_1_fu_1002_p3;

assign tmp_i_i_fu_367_p1 = p_Result_i_i_fu_357_p4;

assign tmp_s_fu_533_p1 = sh_assign_reg_285;

assign tmp_s_out_fu_1350_p1 = p_Result_6_fu_1342_p4;

assign tx_V_fu_794_p2 = (p_Val2_5_reg_273 + p_Val2_23_fu_787_p3);

assign ty_V_fu_812_p2 = (p_Val2_6_reg_261 + p_Val2_24_fu_805_p3);

assign tz_V_fu_866_p2 = ($signed(p_Val2_7_reg_251) + $signed(p_Val2_cast_fu_862_p1));

assign x_s_V_fu_543_p2 = $signed(p_Val2_5_reg_273) >>> tmp_s_fu_533_p1;

assign y_s_V_fu_537_p2 = $signed(p_Val2_6_reg_261) >>> tmp_s_fu_533_p1;

always @ (posedge ap_clk) begin
    r_V_5_reg_1517[52] <= 1'b1;
    p_Val2_13_reg_1577[0] <= 1'b0;
    p_Val2_16_reg_1583[0] <= 1'b0;
end

endmodule //sin_cos_range_redux_s
