// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "big_mult_v3small.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic big_mult_v3small::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic big_mult_v3small::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state1 = "1";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state2 = "10";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state3 = "100";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state4 = "1000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state5 = "10000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state6 = "100000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state7 = "1000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state8 = "10000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state9 = "100000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state10 = "1000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state11 = "10000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state12 = "100000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<24> big_mult_v3small::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<32> big_mult_v3small::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> big_mult_v3small::ap_const_lv1_1 = "1";
const sc_lv<32> big_mult_v3small::ap_const_lv32_1 = "1";
const sc_lv<1> big_mult_v3small::ap_const_lv1_0 = "0";
const sc_lv<32> big_mult_v3small::ap_const_lv32_2 = "10";
const sc_lv<32> big_mult_v3small::ap_const_lv32_13 = "10011";
const sc_lv<32> big_mult_v3small::ap_const_lv32_15 = "10101";
const sc_lv<32> big_mult_v3small::ap_const_lv32_16 = "10110";
const sc_lv<32> big_mult_v3small::ap_const_lv32_11 = "10001";
const sc_lv<4> big_mult_v3small::ap_const_lv4_0 = "0000";
const sc_lv<4> big_mult_v3small::ap_const_lv4_1 = "1";
const sc_lv<32> big_mult_v3small::ap_const_lv32_12 = "10010";
const sc_lv<32> big_mult_v3small::ap_const_lv32_14 = "10100";
const sc_lv<3> big_mult_v3small::ap_const_lv3_0 = "000";
const sc_lv<64> big_mult_v3small::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> big_mult_v3small::ap_const_lv64_7 = "111";
const sc_lv<4> big_mult_v3small::ap_const_lv4_8 = "1000";
const sc_lv<4> big_mult_v3small::ap_const_lv4_7 = "111";
const sc_lv<7> big_mult_v3small::ap_const_lv7_10 = "10000";
const sc_lv<7> big_mult_v3small::ap_const_lv7_7C = "1111100";
const sc_lv<32> big_mult_v3small::ap_const_lv32_7C = "1111100";
const sc_lv<125> big_mult_v3small::ap_const_lv125_1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<32> big_mult_v3small::ap_const_lv32_3 = "11";
const sc_lv<4> big_mult_v3small::ap_const_lv4_F = "1111";
const sc_lv<32> big_mult_v3small::ap_const_lv32_45 = "1000101";
const sc_lv<3> big_mult_v3small::ap_const_lv3_7 = "111";
const sc_lv<3> big_mult_v3small::ap_const_lv3_1 = "1";
const sc_lv<7> big_mult_v3small::ap_const_lv7_6F = "1101111";
const sc_lv<8> big_mult_v3small::ap_const_lv8_B1 = "10110001";
const sc_lv<32> big_mult_v3small::ap_const_lv32_B1 = "10110001";
const sc_lv<178> big_mult_v3small::ap_const_lv178_lc_1 = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<32> big_mult_v3small::ap_const_lv32_17 = "10111";
const sc_lv<32> big_mult_v3small::ap_const_lv32_77 = "1110111";
const sc_lv<178> big_mult_v3small::ap_const_lv178_lc_2 = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

big_mult_v3small::big_mult_v3small(sc_module_name name) : sc_module(name), mVcdFile(0) {
    pp_V_U = new big_mult_v3small_bkb("pp_V_U");
    pp_V_U->clk(ap_clk);
    pp_V_U->reset(ap_rst);
    pp_V_U->address0(pp_V_address0);
    pp_V_U->ce0(pp_V_ce0);
    pp_V_U->we0(pp_V_we0);
    pp_V_U->d0(grp_fu_341_p2);
    pp_V_U->q0(pp_V_q0);
    pps_V_U = new big_mult_v3small_bkb("pps_V_U");
    pps_V_U->clk(ap_clk);
    pps_V_U->reset(ap_rst);
    pps_V_U->address0(pps_V_address0);
    pps_V_U->ce0(pps_V_ce0);
    pps_V_U->we0(pps_V_we0);
    pps_V_U->d0(pps_V_d0);
    pps_V_U->q0(pps_V_q0);
    s_compute_acoustidEe_U1 = new s_compute_acoustidEe<1,15,53,70,70>("s_compute_acoustidEe_U1");
    s_compute_acoustidEe_U1->clk(ap_clk);
    s_compute_acoustidEe_U1->reset(ap_rst);
    s_compute_acoustidEe_U1->din0(grp_fu_341_p0);
    s_compute_acoustidEe_U1->din1(tmp_335_reg_625);
    s_compute_acoustidEe_U1->ce(ap_var_for_const0);
    s_compute_acoustidEe_U1->dout(grp_fu_341_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Li_fu_417_p4);
    sensitive << ( i_2_reg_197 );

    SC_METHOD(thread_Lo_assign_fu_235_p3);
    sensitive << ( i_reg_162 );
    sensitive << ( tmp_320_fu_231_p1 );

    SC_METHOD(thread_Ui_1_fu_427_p2);
    sensitive << ( Li_fu_417_p4 );

    SC_METHOD(thread_Ui_fu_249_p3);
    sensitive << ( tmp_s_fu_225_p2 );
    sensitive << ( tmp_172_fu_243_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( p_Result_s_fu_573_p5 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_exitcond1_fu_213_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_162 );

    SC_METHOD(thread_exitcond2_fu_351_p2);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( i_1_reg_174 );

    SC_METHOD(thread_exitcond_fu_400_p2);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( i_2_reg_197 );

    SC_METHOD(thread_grp_fu_341_p0);
    sensitive << ( tmp_reg_591 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_i_10_fu_373_p2);
    sensitive << ( i_1_reg_174 );

    SC_METHOD(thread_i_9_fu_219_p2);
    sensitive << ( i_reg_162 );

    SC_METHOD(thread_loc_V_fu_437_p1);
    sensitive << ( tmp_337_fu_433_p1 );

    SC_METHOD(thread_p_Result_14_fu_563_p2);
    sensitive << ( tmp_355_fu_551_p2 );
    sensitive << ( tmp_356_fu_557_p2 );

    SC_METHOD(thread_p_Result_15_fu_331_p2);
    sensitive << ( tmp_332_fu_319_p2 );
    sensitive << ( tmp_333_fu_325_p2 );

    SC_METHOD(thread_p_Result_s_fu_573_p5);
    sensitive << ( p_Val2_s_reg_185 );
    sensitive << ( tmp_336_fu_569_p1 );

    SC_METHOD(thread_p_demorgan_fu_539_p2);
    sensitive << ( tmp_352_fu_527_p2 );
    sensitive << ( tmp_353_fu_533_p2 );

    SC_METHOD(thread_pp_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_176_fu_357_p1 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( tmp_173_fu_346_p1 );

    SC_METHOD(thread_pp_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_pp_V_we0);
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_pps_V_address0);
    sensitive << ( tmp_176_reg_633 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( exitcond_fu_400_p2 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_178_fu_368_p1 );
    sensitive << ( tmp_180_fu_412_p1 );

    SC_METHOD(thread_pps_V_ce0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( exitcond_fu_400_p2 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_pps_V_d0);
    sensitive << ( pp_V_q0 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_179_fu_393_p2 );

    SC_METHOD(thread_pps_V_we0);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_r_V_7_fu_389_p1);
    sensitive << ( r_V_fu_379_p4 );

    SC_METHOD(thread_r_V_fu_379_p4);
    sensitive << ( pps_V_q0 );

    SC_METHOD(thread_tmp_172_fu_243_p2);
    sensitive << ( Lo_assign_fu_235_p3 );

    SC_METHOD(thread_tmp_173_fu_346_p1);
    sensitive << ( i_reg_162 );

    SC_METHOD(thread_tmp_176_fu_357_p1);
    sensitive << ( i_1_reg_174 );

    SC_METHOD(thread_tmp_177_fu_362_p2);
    sensitive << ( i_1_reg_174 );

    SC_METHOD(thread_tmp_178_fu_368_p1);
    sensitive << ( tmp_177_fu_362_p2 );

    SC_METHOD(thread_tmp_179_fu_393_p2);
    sensitive << ( pp_V_q0 );
    sensitive << ( r_V_7_fu_389_p1 );

    SC_METHOD(thread_tmp_180_fu_412_p1);
    sensitive << ( i_2_reg_197 );

    SC_METHOD(thread_tmp_181_fu_406_p2);
    sensitive << ( i_2_reg_197 );

    SC_METHOD(thread_tmp_320_fu_231_p1);
    sensitive << ( i_reg_162 );

    SC_METHOD(thread_tmp_321_fu_257_p2);
    sensitive << ( Lo_assign_reg_604 );
    sensitive << ( Ui_reg_613 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_322_fu_261_p4);
    sensitive << ( a_V );

    SC_METHOD(thread_tmp_323_fu_270_p2);
    sensitive << ( Lo_assign_reg_604 );
    sensitive << ( Ui_reg_613 );

    SC_METHOD(thread_tmp_324_fu_274_p2);
    sensitive << ( Lo_assign_reg_604 );

    SC_METHOD(thread_tmp_325_fu_279_p2);
    sensitive << ( Lo_assign_reg_604 );
    sensitive << ( Ui_reg_613 );

    SC_METHOD(thread_tmp_326_fu_283_p3);
    sensitive << ( tmp_321_fu_257_p2 );
    sensitive << ( tmp_323_fu_270_p2 );
    sensitive << ( tmp_325_fu_279_p2 );

    SC_METHOD(thread_tmp_327_fu_291_p3);
    sensitive << ( a_V );
    sensitive << ( tmp_321_fu_257_p2 );
    sensitive << ( tmp_322_fu_261_p4 );

    SC_METHOD(thread_tmp_328_fu_298_p3);
    sensitive << ( Lo_assign_reg_604 );
    sensitive << ( tmp_321_fu_257_p2 );
    sensitive << ( tmp_324_fu_274_p2 );

    SC_METHOD(thread_tmp_329_fu_305_p2);
    sensitive << ( tmp_326_fu_283_p3 );

    SC_METHOD(thread_tmp_330_fu_311_p1);
    sensitive << ( tmp_328_fu_298_p3 );

    SC_METHOD(thread_tmp_331_fu_315_p1);
    sensitive << ( tmp_329_fu_305_p2 );

    SC_METHOD(thread_tmp_332_fu_319_p2);
    sensitive << ( tmp_327_fu_291_p3 );
    sensitive << ( tmp_330_fu_311_p1 );

    SC_METHOD(thread_tmp_333_fu_325_p2);
    sensitive << ( tmp_331_fu_315_p1 );

    SC_METHOD(thread_tmp_335_fu_337_p1);
    sensitive << ( p_Result_15_fu_331_p2 );

    SC_METHOD(thread_tmp_336_fu_569_p1);
    sensitive << ( pps_V_q0 );

    SC_METHOD(thread_tmp_337_fu_433_p1);
    sensitive << ( pps_V_q0 );

    SC_METHOD(thread_tmp_338_fu_441_p2);
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( Li_fu_417_p4 );

    SC_METHOD(thread_tmp_339_fu_447_p1);
    sensitive << ( Li_fu_417_p4 );

    SC_METHOD(thread_tmp_340_fu_451_p1);
    sensitive << ( Ui_1_fu_427_p2 );

    SC_METHOD(thread_tmp_341_fu_455_p2);
    sensitive << ( tmp_339_fu_447_p1 );

    SC_METHOD(thread_tmp_342_fu_461_p3);
    sensitive << ( tmp_339_fu_447_p1 );
    sensitive << ( tmp_338_fu_441_p2 );
    sensitive << ( tmp_340_fu_451_p1 );

    SC_METHOD(thread_tmp_343_fu_469_p3);
    sensitive << ( tmp_339_fu_447_p1 );
    sensitive << ( tmp_338_fu_441_p2 );
    sensitive << ( tmp_340_fu_451_p1 );

    SC_METHOD(thread_tmp_344_fu_477_p3);
    sensitive << ( tmp_339_fu_447_p1 );
    sensitive << ( tmp_338_fu_441_p2 );
    sensitive << ( tmp_341_fu_455_p2 );

    SC_METHOD(thread_tmp_345_fu_485_p2);
    sensitive << ( tmp_342_fu_461_p3 );

    SC_METHOD(thread_tmp_346_fu_491_p1);
    sensitive << ( tmp_344_fu_477_p3 );

    SC_METHOD(thread_tmp_347_fu_495_p1);
    sensitive << ( tmp_343_fu_469_p3 );

    SC_METHOD(thread_tmp_348_fu_499_p1);
    sensitive << ( tmp_345_fu_485_p2 );

    SC_METHOD(thread_tmp_349_fu_503_p2);
    sensitive << ( loc_V_fu_437_p1 );
    sensitive << ( tmp_346_fu_491_p1 );

    SC_METHOD(thread_tmp_350_fu_509_p4);
    sensitive << ( tmp_349_fu_503_p2 );

    SC_METHOD(thread_tmp_351_fu_519_p3);
    sensitive << ( tmp_338_fu_441_p2 );
    sensitive << ( tmp_349_fu_503_p2 );
    sensitive << ( tmp_350_fu_509_p4 );

    SC_METHOD(thread_tmp_352_fu_527_p2);
    sensitive << ( tmp_347_fu_495_p1 );

    SC_METHOD(thread_tmp_353_fu_533_p2);
    sensitive << ( tmp_348_fu_499_p1 );

    SC_METHOD(thread_tmp_354_fu_545_p2);
    sensitive << ( p_demorgan_fu_539_p2 );

    SC_METHOD(thread_tmp_355_fu_551_p2);
    sensitive << ( p_Val2_s_reg_185 );
    sensitive << ( tmp_354_fu_545_p2 );

    SC_METHOD(thread_tmp_356_fu_557_p2);
    sensitive << ( p_demorgan_fu_539_p2 );
    sensitive << ( tmp_351_fu_519_p3 );

    SC_METHOD(thread_tmp_fu_209_p1);
    sensitive << ( b_V );

    SC_METHOD(thread_tmp_s_fu_225_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_213_p2 );
    sensitive << ( i_reg_162 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_213_p2 );
    sensitive << ( exitcond2_fu_351_p2 );
    sensitive << ( exitcond_fu_400_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000000000001";
    ap_return_preg = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "big_mult_v3small_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_V, "(port)a_V");
    sc_trace(mVcdFile, b_V, "(port)b_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_fu_209_p1, "tmp_fu_209_p1");
    sc_trace(mVcdFile, tmp_reg_591, "tmp_reg_591");
    sc_trace(mVcdFile, i_9_fu_219_p2, "i_9_fu_219_p2");
    sc_trace(mVcdFile, i_9_reg_599, "i_9_reg_599");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, Lo_assign_fu_235_p3, "Lo_assign_fu_235_p3");
    sc_trace(mVcdFile, Lo_assign_reg_604, "Lo_assign_reg_604");
    sc_trace(mVcdFile, exitcond1_fu_213_p2, "exitcond1_fu_213_p2");
    sc_trace(mVcdFile, Ui_fu_249_p3, "Ui_fu_249_p3");
    sc_trace(mVcdFile, Ui_reg_613, "Ui_reg_613");
    sc_trace(mVcdFile, tmp_335_fu_337_p1, "tmp_335_fu_337_p1");
    sc_trace(mVcdFile, tmp_335_reg_625, "tmp_335_reg_625");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_176_fu_357_p1, "tmp_176_fu_357_p1");
    sc_trace(mVcdFile, tmp_176_reg_633, "tmp_176_reg_633");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, exitcond2_fu_351_p2, "exitcond2_fu_351_p2");
    sc_trace(mVcdFile, i_10_fu_373_p2, "i_10_fu_373_p2");
    sc_trace(mVcdFile, i_10_reg_648, "i_10_reg_648");
    sc_trace(mVcdFile, tmp_181_fu_406_p2, "tmp_181_fu_406_p2");
    sc_trace(mVcdFile, tmp_181_reg_656, "tmp_181_reg_656");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, exitcond_fu_400_p2, "exitcond_fu_400_p2");
    sc_trace(mVcdFile, p_Result_14_fu_563_p2, "p_Result_14_fu_563_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, pp_V_address0, "pp_V_address0");
    sc_trace(mVcdFile, pp_V_ce0, "pp_V_ce0");
    sc_trace(mVcdFile, pp_V_we0, "pp_V_we0");
    sc_trace(mVcdFile, pp_V_q0, "pp_V_q0");
    sc_trace(mVcdFile, pps_V_address0, "pps_V_address0");
    sc_trace(mVcdFile, pps_V_ce0, "pps_V_ce0");
    sc_trace(mVcdFile, pps_V_we0, "pps_V_we0");
    sc_trace(mVcdFile, pps_V_d0, "pps_V_d0");
    sc_trace(mVcdFile, pps_V_q0, "pps_V_q0");
    sc_trace(mVcdFile, i_reg_162, "i_reg_162");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, i_1_reg_174, "i_1_reg_174");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, p_Val2_s_reg_185, "p_Val2_s_reg_185");
    sc_trace(mVcdFile, i_2_reg_197, "i_2_reg_197");
    sc_trace(mVcdFile, tmp_173_fu_346_p1, "tmp_173_fu_346_p1");
    sc_trace(mVcdFile, tmp_178_fu_368_p1, "tmp_178_fu_368_p1");
    sc_trace(mVcdFile, tmp_180_fu_412_p1, "tmp_180_fu_412_p1");
    sc_trace(mVcdFile, grp_fu_341_p2, "grp_fu_341_p2");
    sc_trace(mVcdFile, tmp_179_fu_393_p2, "tmp_179_fu_393_p2");
    sc_trace(mVcdFile, tmp_320_fu_231_p1, "tmp_320_fu_231_p1");
    sc_trace(mVcdFile, tmp_s_fu_225_p2, "tmp_s_fu_225_p2");
    sc_trace(mVcdFile, tmp_172_fu_243_p2, "tmp_172_fu_243_p2");
    sc_trace(mVcdFile, tmp_321_fu_257_p2, "tmp_321_fu_257_p2");
    sc_trace(mVcdFile, tmp_323_fu_270_p2, "tmp_323_fu_270_p2");
    sc_trace(mVcdFile, tmp_325_fu_279_p2, "tmp_325_fu_279_p2");
    sc_trace(mVcdFile, tmp_322_fu_261_p4, "tmp_322_fu_261_p4");
    sc_trace(mVcdFile, tmp_324_fu_274_p2, "tmp_324_fu_274_p2");
    sc_trace(mVcdFile, tmp_326_fu_283_p3, "tmp_326_fu_283_p3");
    sc_trace(mVcdFile, tmp_328_fu_298_p3, "tmp_328_fu_298_p3");
    sc_trace(mVcdFile, tmp_329_fu_305_p2, "tmp_329_fu_305_p2");
    sc_trace(mVcdFile, tmp_327_fu_291_p3, "tmp_327_fu_291_p3");
    sc_trace(mVcdFile, tmp_330_fu_311_p1, "tmp_330_fu_311_p1");
    sc_trace(mVcdFile, tmp_331_fu_315_p1, "tmp_331_fu_315_p1");
    sc_trace(mVcdFile, tmp_332_fu_319_p2, "tmp_332_fu_319_p2");
    sc_trace(mVcdFile, tmp_333_fu_325_p2, "tmp_333_fu_325_p2");
    sc_trace(mVcdFile, p_Result_15_fu_331_p2, "p_Result_15_fu_331_p2");
    sc_trace(mVcdFile, grp_fu_341_p0, "grp_fu_341_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_177_fu_362_p2, "tmp_177_fu_362_p2");
    sc_trace(mVcdFile, r_V_fu_379_p4, "r_V_fu_379_p4");
    sc_trace(mVcdFile, r_V_7_fu_389_p1, "r_V_7_fu_389_p1");
    sc_trace(mVcdFile, Li_fu_417_p4, "Li_fu_417_p4");
    sc_trace(mVcdFile, tmp_337_fu_433_p1, "tmp_337_fu_433_p1");
    sc_trace(mVcdFile, Ui_1_fu_427_p2, "Ui_1_fu_427_p2");
    sc_trace(mVcdFile, tmp_339_fu_447_p1, "tmp_339_fu_447_p1");
    sc_trace(mVcdFile, tmp_338_fu_441_p2, "tmp_338_fu_441_p2");
    sc_trace(mVcdFile, tmp_340_fu_451_p1, "tmp_340_fu_451_p1");
    sc_trace(mVcdFile, tmp_341_fu_455_p2, "tmp_341_fu_455_p2");
    sc_trace(mVcdFile, tmp_342_fu_461_p3, "tmp_342_fu_461_p3");
    sc_trace(mVcdFile, tmp_344_fu_477_p3, "tmp_344_fu_477_p3");
    sc_trace(mVcdFile, tmp_343_fu_469_p3, "tmp_343_fu_469_p3");
    sc_trace(mVcdFile, tmp_345_fu_485_p2, "tmp_345_fu_485_p2");
    sc_trace(mVcdFile, loc_V_fu_437_p1, "loc_V_fu_437_p1");
    sc_trace(mVcdFile, tmp_346_fu_491_p1, "tmp_346_fu_491_p1");
    sc_trace(mVcdFile, tmp_349_fu_503_p2, "tmp_349_fu_503_p2");
    sc_trace(mVcdFile, tmp_350_fu_509_p4, "tmp_350_fu_509_p4");
    sc_trace(mVcdFile, tmp_347_fu_495_p1, "tmp_347_fu_495_p1");
    sc_trace(mVcdFile, tmp_348_fu_499_p1, "tmp_348_fu_499_p1");
    sc_trace(mVcdFile, tmp_352_fu_527_p2, "tmp_352_fu_527_p2");
    sc_trace(mVcdFile, tmp_353_fu_533_p2, "tmp_353_fu_533_p2");
    sc_trace(mVcdFile, p_demorgan_fu_539_p2, "p_demorgan_fu_539_p2");
    sc_trace(mVcdFile, tmp_354_fu_545_p2, "tmp_354_fu_545_p2");
    sc_trace(mVcdFile, tmp_351_fu_519_p3, "tmp_351_fu_519_p3");
    sc_trace(mVcdFile, tmp_355_fu_551_p2, "tmp_355_fu_551_p2");
    sc_trace(mVcdFile, tmp_356_fu_557_p2, "tmp_356_fu_557_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, tmp_336_fu_569_p1, "tmp_336_fu_569_p1");
    sc_trace(mVcdFile, p_Result_s_fu_573_p5, "p_Result_s_fu_573_p5");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

big_mult_v3small::~big_mult_v3small() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete pp_V_U;
    delete pps_V_U;
    delete s_compute_acoustidEe_U1;
}

void big_mult_v3small::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void big_mult_v3small::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv178_lc_2;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()))) {
            ap_return_preg = p_Result_s_fu_573_p5.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        i_1_reg_174 = i_10_reg_648.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read()))) {
        i_1_reg_174 = ap_const_lv4_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state20.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_351_p2.read()))) {
        i_2_reg_197 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read()))) {
        i_2_reg_197 = tmp_181_reg_656.read();
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_162 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read()))) {
        i_reg_162 = i_9_reg_599.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_213_p2.read(), ap_const_lv1_0))) {
        Lo_assign_reg_604 = Lo_assign_fu_235_p3.read();
        Ui_reg_613 = Ui_fu_249_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state20.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_351_p2.read()))) {
        i_10_reg_648 = i_10_fu_373_p2.read();
        tmp_176_reg_633 = tmp_176_fu_357_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        i_9_reg_599 = i_9_fu_219_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read()))) {
        p_Val2_s_reg_185 = p_Result_14_fu_563_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        tmp_181_reg_656 = tmp_181_fu_406_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        tmp_335_reg_625 = tmp_335_fu_337_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        tmp_reg_591 = tmp_fu_209_p1.read();
    }
}

void big_mult_v3small::thread_Li_fu_417_p4() {
    Li_fu_417_p4 = esl_concat<4,3>(esl_concat<3,1>(i_2_reg_197.read(), ap_const_lv1_0), i_2_reg_197.read());
}

void big_mult_v3small::thread_Lo_assign_fu_235_p3() {
    Lo_assign_fu_235_p3 = esl_concat<3,4>(tmp_320_fu_231_p1.read(), i_reg_162.read());
}

void big_mult_v3small::thread_Ui_1_fu_427_p2() {
    Ui_1_fu_427_p2 = (!ap_const_lv7_10.is_01() || !Li_fu_417_p4.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_10) + sc_biguint<7>(Li_fu_417_p4.read()));
}

void big_mult_v3small::thread_Ui_fu_249_p3() {
    Ui_fu_249_p3 = (!tmp_s_fu_225_p2.read()[0].is_01())? sc_lv<7>(): ((tmp_s_fu_225_p2.read()[0].to_bool())? ap_const_lv7_7C: tmp_172_fu_243_p2.read());
}

void big_mult_v3small::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void big_mult_v3small::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read().range(17, 17);
}

void big_mult_v3small::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read().range(18, 18);
}

void big_mult_v3small::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void big_mult_v3small::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read().range(19, 19);
}

void big_mult_v3small::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read().range(20, 20);
}

void big_mult_v3small::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read().range(21, 21);
}

void big_mult_v3small::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read().range(22, 22);
}

void big_mult_v3small::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read().range(23, 23);
}

void big_mult_v3small::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void big_mult_v3small::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read().range(3, 3);
}

void big_mult_v3small::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void big_mult_v3small::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void big_mult_v3small::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void big_mult_v3small::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()))) {
        ap_return = p_Result_s_fu_573_p5.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void big_mult_v3small::thread_exitcond1_fu_213_p2() {
    exitcond1_fu_213_p2 = (!i_reg_162.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_162.read() == ap_const_lv4_8);
}

void big_mult_v3small::thread_exitcond2_fu_351_p2() {
    exitcond2_fu_351_p2 = (!i_1_reg_174.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_174.read() == ap_const_lv4_8);
}

void big_mult_v3small::thread_exitcond_fu_400_p2() {
    exitcond_fu_400_p2 = (!i_2_reg_197.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_197.read() == ap_const_lv3_7);
}

void big_mult_v3small::thread_grp_fu_341_p0() {
    grp_fu_341_p0 =  (sc_lv<53>) (tmp_reg_591.read());
}

void big_mult_v3small::thread_i_10_fu_373_p2() {
    i_10_fu_373_p2 = (!i_1_reg_174.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_1_reg_174.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void big_mult_v3small::thread_i_9_fu_219_p2() {
    i_9_fu_219_p2 = (!i_reg_162.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_162.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void big_mult_v3small::thread_loc_V_fu_437_p1() {
    loc_V_fu_437_p1 = esl_zext<178,17>(tmp_337_fu_433_p1.read());
}

void big_mult_v3small::thread_p_Result_14_fu_563_p2() {
    p_Result_14_fu_563_p2 = (tmp_355_fu_551_p2.read() | tmp_356_fu_557_p2.read());
}

void big_mult_v3small::thread_p_Result_15_fu_331_p2() {
    p_Result_15_fu_331_p2 = (tmp_332_fu_319_p2.read() & tmp_333_fu_325_p2.read());
}

void big_mult_v3small::thread_p_Result_s_fu_573_p5() {
    p_Result_s_fu_573_p5 = esl_partset<178,178,59,32,32>(p_Val2_s_reg_185.read(), tmp_336_fu_569_p1.read(), ap_const_lv32_77, ap_const_lv32_B1);
}

void big_mult_v3small::thread_p_demorgan_fu_539_p2() {
    p_demorgan_fu_539_p2 = (tmp_352_fu_527_p2.read() & tmp_353_fu_533_p2.read());
}

void big_mult_v3small::thread_pp_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state20.read()))) {
        pp_V_address0 =  (sc_lv<3>) (tmp_176_fu_357_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read()))) {
        pp_V_address0 =  (sc_lv<3>) (tmp_173_fu_346_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        pp_V_address0 =  (sc_lv<3>) (ap_const_lv64_0);
    } else {
        pp_V_address0 = "XXX";
    }
}

void big_mult_v3small::thread_pp_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state20.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read())))) {
        pp_V_ce0 = ap_const_logic_1;
    } else {
        pp_V_ce0 = ap_const_logic_0;
    }
}

void big_mult_v3small::thread_pp_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read())))) {
        pp_V_we0 = ap_const_logic_1;
    } else {
        pp_V_we0 = ap_const_logic_0;
    }
}

void big_mult_v3small::thread_pps_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_400_p2.read()))) {
        pps_V_address0 =  (sc_lv<3>) (ap_const_lv64_7);
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_400_p2.read()))) {
        pps_V_address0 =  (sc_lv<3>) (tmp_180_fu_412_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        pps_V_address0 =  (sc_lv<3>) (tmp_176_reg_633.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state20.read()))) {
        pps_V_address0 =  (sc_lv<3>) (tmp_178_fu_368_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read()))) {
        pps_V_address0 =  (sc_lv<3>) (ap_const_lv64_0);
    } else {
        pps_V_address0 = "XXX";
    }
}

void big_mult_v3small::thread_pps_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state20.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_400_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_400_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read())))) {
        pps_V_ce0 = ap_const_logic_1;
    } else {
        pps_V_ce0 = ap_const_logic_0;
    }
}

void big_mult_v3small::thread_pps_V_d0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        pps_V_d0 = tmp_179_fu_393_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read()))) {
        pps_V_d0 = pp_V_q0.read();
    } else {
        pps_V_d0 =  (sc_lv<70>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void big_mult_v3small::thread_pps_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read())))) {
        pps_V_we0 = ap_const_logic_1;
    } else {
        pps_V_we0 = ap_const_logic_0;
    }
}

void big_mult_v3small::thread_r_V_7_fu_389_p1() {
    r_V_7_fu_389_p1 = esl_zext<70,53>(r_V_fu_379_p4.read());
}

void big_mult_v3small::thread_r_V_fu_379_p4() {
    r_V_fu_379_p4 = pps_V_q0.read().range(69, 17);
}

void big_mult_v3small::thread_tmp_172_fu_243_p2() {
    tmp_172_fu_243_p2 = (!ap_const_lv7_10.is_01() || !Lo_assign_fu_235_p3.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_10) + sc_biguint<7>(Lo_assign_fu_235_p3.read()));
}

void big_mult_v3small::thread_tmp_173_fu_346_p1() {
    tmp_173_fu_346_p1 = esl_zext<64,4>(i_reg_162.read());
}

void big_mult_v3small::thread_tmp_176_fu_357_p1() {
    tmp_176_fu_357_p1 = esl_zext<64,4>(i_1_reg_174.read());
}

void big_mult_v3small::thread_tmp_177_fu_362_p2() {
    tmp_177_fu_362_p2 = (!i_1_reg_174.read().is_01() || !ap_const_lv4_F.is_01())? sc_lv<4>(): (sc_biguint<4>(i_1_reg_174.read()) + sc_bigint<4>(ap_const_lv4_F));
}

void big_mult_v3small::thread_tmp_178_fu_368_p1() {
    tmp_178_fu_368_p1 = esl_zext<64,4>(tmp_177_fu_362_p2.read());
}

void big_mult_v3small::thread_tmp_179_fu_393_p2() {
    tmp_179_fu_393_p2 = (!pp_V_q0.read().is_01() || !r_V_7_fu_389_p1.read().is_01())? sc_lv<70>(): (sc_biguint<70>(pp_V_q0.read()) + sc_biguint<70>(r_V_7_fu_389_p1.read()));
}

void big_mult_v3small::thread_tmp_180_fu_412_p1() {
    tmp_180_fu_412_p1 = esl_zext<64,3>(i_2_reg_197.read());
}

void big_mult_v3small::thread_tmp_181_fu_406_p2() {
    tmp_181_fu_406_p2 = (!i_2_reg_197.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_2_reg_197.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void big_mult_v3small::thread_tmp_320_fu_231_p1() {
    tmp_320_fu_231_p1 = i_reg_162.read().range(3-1, 0);
}

void big_mult_v3small::thread_tmp_321_fu_257_p2() {
    tmp_321_fu_257_p2 = (!Lo_assign_reg_604.read().is_01() || !Ui_reg_613.read().is_01())? sc_lv<1>(): (sc_biguint<7>(Lo_assign_reg_604.read()) > sc_biguint<7>(Ui_reg_613.read()));
}

void big_mult_v3small::thread_tmp_322_fu_261_p4() {
    tmp_322_fu_261_p4 = a_V.read().range(0, 124);
}

void big_mult_v3small::thread_tmp_323_fu_270_p2() {
    tmp_323_fu_270_p2 = (!Lo_assign_reg_604.read().is_01() || !Ui_reg_613.read().is_01())? sc_lv<7>(): (sc_biguint<7>(Lo_assign_reg_604.read()) - sc_biguint<7>(Ui_reg_613.read()));
}

void big_mult_v3small::thread_tmp_324_fu_274_p2() {
    tmp_324_fu_274_p2 = (!ap_const_lv7_7C.is_01() || !Lo_assign_reg_604.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_7C) - sc_biguint<7>(Lo_assign_reg_604.read()));
}

void big_mult_v3small::thread_tmp_325_fu_279_p2() {
    tmp_325_fu_279_p2 = (!Ui_reg_613.read().is_01() || !Lo_assign_reg_604.read().is_01())? sc_lv<7>(): (sc_biguint<7>(Ui_reg_613.read()) - sc_biguint<7>(Lo_assign_reg_604.read()));
}

void big_mult_v3small::thread_tmp_326_fu_283_p3() {
    tmp_326_fu_283_p3 = (!tmp_321_fu_257_p2.read()[0].is_01())? sc_lv<7>(): ((tmp_321_fu_257_p2.read()[0].to_bool())? tmp_323_fu_270_p2.read(): tmp_325_fu_279_p2.read());
}

void big_mult_v3small::thread_tmp_327_fu_291_p3() {
    tmp_327_fu_291_p3 = (!tmp_321_fu_257_p2.read()[0].is_01())? sc_lv<125>(): ((tmp_321_fu_257_p2.read()[0].to_bool())? tmp_322_fu_261_p4.read(): a_V.read());
}

void big_mult_v3small::thread_tmp_328_fu_298_p3() {
    tmp_328_fu_298_p3 = (!tmp_321_fu_257_p2.read()[0].is_01())? sc_lv<7>(): ((tmp_321_fu_257_p2.read()[0].to_bool())? tmp_324_fu_274_p2.read(): Lo_assign_reg_604.read());
}

void big_mult_v3small::thread_tmp_329_fu_305_p2() {
    tmp_329_fu_305_p2 = (!ap_const_lv7_7C.is_01() || !tmp_326_fu_283_p3.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_7C) - sc_biguint<7>(tmp_326_fu_283_p3.read()));
}

void big_mult_v3small::thread_tmp_330_fu_311_p1() {
    tmp_330_fu_311_p1 = esl_zext<125,7>(tmp_328_fu_298_p3.read());
}

void big_mult_v3small::thread_tmp_331_fu_315_p1() {
    tmp_331_fu_315_p1 = esl_zext<125,7>(tmp_329_fu_305_p2.read());
}

void big_mult_v3small::thread_tmp_332_fu_319_p2() {
    tmp_332_fu_319_p2 = (!tmp_330_fu_311_p1.read().is_01())? sc_lv<125>(): tmp_327_fu_291_p3.read() >> (unsigned short)tmp_330_fu_311_p1.read().to_uint();
}

void big_mult_v3small::thread_tmp_333_fu_325_p2() {
    tmp_333_fu_325_p2 = (!tmp_331_fu_315_p1.read().is_01())? sc_lv<125>(): ap_const_lv125_1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF >> (unsigned short)tmp_331_fu_315_p1.read().to_uint();
}

void big_mult_v3small::thread_tmp_335_fu_337_p1() {
    tmp_335_fu_337_p1 = p_Result_15_fu_331_p2.read().range(70-1, 0);
}

void big_mult_v3small::thread_tmp_336_fu_569_p1() {
    tmp_336_fu_569_p1 = pps_V_q0.read().range(59-1, 0);
}

void big_mult_v3small::thread_tmp_337_fu_433_p1() {
    tmp_337_fu_433_p1 = pps_V_q0.read().range(17-1, 0);
}

void big_mult_v3small::thread_tmp_338_fu_441_p2() {
    tmp_338_fu_441_p2 = (!Li_fu_417_p4.read().is_01() || !ap_const_lv7_6F.is_01())? sc_lv<1>(): (sc_biguint<7>(Li_fu_417_p4.read()) > sc_biguint<7>(ap_const_lv7_6F));
}

void big_mult_v3small::thread_tmp_339_fu_447_p1() {
    tmp_339_fu_447_p1 = esl_zext<8,7>(Li_fu_417_p4.read());
}

void big_mult_v3small::thread_tmp_340_fu_451_p1() {
    tmp_340_fu_451_p1 = esl_zext<8,7>(Ui_1_fu_427_p2.read());
}

void big_mult_v3small::thread_tmp_341_fu_455_p2() {
    tmp_341_fu_455_p2 = (!ap_const_lv8_B1.is_01() || !tmp_339_fu_447_p1.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_B1) - sc_biguint<8>(tmp_339_fu_447_p1.read()));
}

void big_mult_v3small::thread_tmp_342_fu_461_p3() {
    tmp_342_fu_461_p3 = (!tmp_338_fu_441_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_338_fu_441_p2.read()[0].to_bool())? tmp_339_fu_447_p1.read(): tmp_340_fu_451_p1.read());
}

void big_mult_v3small::thread_tmp_343_fu_469_p3() {
    tmp_343_fu_469_p3 = (!tmp_338_fu_441_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_338_fu_441_p2.read()[0].to_bool())? tmp_340_fu_451_p1.read(): tmp_339_fu_447_p1.read());
}

void big_mult_v3small::thread_tmp_344_fu_477_p3() {
    tmp_344_fu_477_p3 = (!tmp_338_fu_441_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_338_fu_441_p2.read()[0].to_bool())? tmp_341_fu_455_p2.read(): tmp_339_fu_447_p1.read());
}

void big_mult_v3small::thread_tmp_345_fu_485_p2() {
    tmp_345_fu_485_p2 = (!ap_const_lv8_B1.is_01() || !tmp_342_fu_461_p3.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_B1) - sc_biguint<8>(tmp_342_fu_461_p3.read()));
}

void big_mult_v3small::thread_tmp_346_fu_491_p1() {
    tmp_346_fu_491_p1 = esl_zext<178,8>(tmp_344_fu_477_p3.read());
}

void big_mult_v3small::thread_tmp_347_fu_495_p1() {
    tmp_347_fu_495_p1 = esl_zext<178,8>(tmp_343_fu_469_p3.read());
}

void big_mult_v3small::thread_tmp_348_fu_499_p1() {
    tmp_348_fu_499_p1 = esl_zext<178,8>(tmp_345_fu_485_p2.read());
}

void big_mult_v3small::thread_tmp_349_fu_503_p2() {
    tmp_349_fu_503_p2 = (!tmp_346_fu_491_p1.read().is_01())? sc_lv<178>(): loc_V_fu_437_p1.read() << (unsigned short)tmp_346_fu_491_p1.read().to_uint();
}

void big_mult_v3small::thread_tmp_350_fu_509_p4() {
    tmp_350_fu_509_p4 = tmp_349_fu_503_p2.read().range(0, 177);
}

void big_mult_v3small::thread_tmp_351_fu_519_p3() {
    tmp_351_fu_519_p3 = (!tmp_338_fu_441_p2.read()[0].is_01())? sc_lv<178>(): ((tmp_338_fu_441_p2.read()[0].to_bool())? tmp_350_fu_509_p4.read(): tmp_349_fu_503_p2.read());
}

void big_mult_v3small::thread_tmp_352_fu_527_p2() {
    tmp_352_fu_527_p2 = (!tmp_347_fu_495_p1.read().is_01())? sc_lv<178>(): ap_const_lv178_lc_1 << (unsigned short)tmp_347_fu_495_p1.read().to_uint();
}

void big_mult_v3small::thread_tmp_353_fu_533_p2() {
    tmp_353_fu_533_p2 = (!tmp_348_fu_499_p1.read().is_01())? sc_lv<178>(): ap_const_lv178_lc_1 >> (unsigned short)tmp_348_fu_499_p1.read().to_uint();
}

void big_mult_v3small::thread_tmp_354_fu_545_p2() {
    tmp_354_fu_545_p2 = (p_demorgan_fu_539_p2.read() ^ ap_const_lv178_lc_1);
}

void big_mult_v3small::thread_tmp_355_fu_551_p2() {
    tmp_355_fu_551_p2 = (p_Val2_s_reg_185.read() & tmp_354_fu_545_p2.read());
}

void big_mult_v3small::thread_tmp_356_fu_557_p2() {
    tmp_356_fu_557_p2 = (tmp_351_fu_519_p3.read() & p_demorgan_fu_539_p2.read());
}

void big_mult_v3small::thread_tmp_fu_209_p1() {
    tmp_fu_209_p1 = esl_zext<70,53>(b_V.read());
}

void big_mult_v3small::thread_tmp_s_fu_225_p2() {
    tmp_s_fu_225_p2 = (!i_reg_162.read().is_01() || !ap_const_lv4_7.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_162.read() == ap_const_lv4_7);
}

void big_mult_v3small::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond1_fu_213_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_351_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state22;
            } else {
                ap_NS_fsm = ap_ST_fsm_state21;
            }
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 2097152 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_400_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state24;
            } else {
                ap_NS_fsm = ap_ST_fsm_state23;
            }
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

