// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _big_mult_v3small_HH_
#define _big_mult_v3small_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "s_compute_acoustidEe.h"
#include "big_mult_v3small_bkb.h"

namespace ap_rtl {

struct big_mult_v3small : public sc_module {
    // Port declarations 9
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<125> > a_V;
    sc_in< sc_lv<53> > b_V;
    sc_out< sc_lv<178> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    big_mult_v3small(sc_module_name name);
    SC_HAS_PROCESS(big_mult_v3small);

    ~big_mult_v3small();

    sc_trace_file* mVcdFile;

    big_mult_v3small_bkb* pp_V_U;
    big_mult_v3small_bkb* pps_V_U;
    s_compute_acoustidEe<1,15,53,70,70>* s_compute_acoustidEe_U1;
    sc_signal< sc_lv<24> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<70> > tmp_fu_209_p1;
    sc_signal< sc_lv<70> > tmp_reg_591;
    sc_signal< sc_lv<4> > i_9_fu_219_p2;
    sc_signal< sc_lv<4> > i_9_reg_599;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<7> > Lo_assign_fu_235_p3;
    sc_signal< sc_lv<7> > Lo_assign_reg_604;
    sc_signal< sc_lv<1> > exitcond1_fu_213_p2;
    sc_signal< sc_lv<7> > Ui_fu_249_p3;
    sc_signal< sc_lv<7> > Ui_reg_613;
    sc_signal< sc_lv<70> > tmp_335_fu_337_p1;
    sc_signal< sc_lv<70> > tmp_335_reg_625;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<64> > tmp_176_fu_357_p1;
    sc_signal< sc_lv<64> > tmp_176_reg_633;
    sc_signal< sc_lv<1> > ap_CS_fsm_state20;
    sc_signal< sc_lv<1> > exitcond2_fu_351_p2;
    sc_signal< sc_lv<4> > i_10_fu_373_p2;
    sc_signal< sc_lv<4> > i_10_reg_648;
    sc_signal< sc_lv<3> > tmp_181_fu_406_p2;
    sc_signal< sc_lv<3> > tmp_181_reg_656;
    sc_signal< sc_lv<1> > ap_CS_fsm_state22;
    sc_signal< sc_lv<1> > exitcond_fu_400_p2;
    sc_signal< sc_lv<178> > p_Result_14_fu_563_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state23;
    sc_signal< sc_lv<3> > pp_V_address0;
    sc_signal< sc_logic > pp_V_ce0;
    sc_signal< sc_logic > pp_V_we0;
    sc_signal< sc_lv<70> > pp_V_q0;
    sc_signal< sc_lv<3> > pps_V_address0;
    sc_signal< sc_logic > pps_V_ce0;
    sc_signal< sc_logic > pps_V_we0;
    sc_signal< sc_lv<70> > pps_V_d0;
    sc_signal< sc_lv<70> > pps_V_q0;
    sc_signal< sc_lv<4> > i_reg_162;
    sc_signal< sc_lv<1> > ap_CS_fsm_state18;
    sc_signal< sc_lv<4> > i_1_reg_174;
    sc_signal< sc_lv<1> > ap_CS_fsm_state19;
    sc_signal< sc_lv<1> > ap_CS_fsm_state21;
    sc_signal< sc_lv<178> > p_Val2_s_reg_185;
    sc_signal< sc_lv<3> > i_2_reg_197;
    sc_signal< sc_lv<64> > tmp_173_fu_346_p1;
    sc_signal< sc_lv<64> > tmp_178_fu_368_p1;
    sc_signal< sc_lv<64> > tmp_180_fu_412_p1;
    sc_signal< sc_lv<70> > grp_fu_341_p2;
    sc_signal< sc_lv<70> > tmp_179_fu_393_p2;
    sc_signal< sc_lv<3> > tmp_320_fu_231_p1;
    sc_signal< sc_lv<1> > tmp_s_fu_225_p2;
    sc_signal< sc_lv<7> > tmp_172_fu_243_p2;
    sc_signal< sc_lv<1> > tmp_321_fu_257_p2;
    sc_signal< sc_lv<7> > tmp_323_fu_270_p2;
    sc_signal< sc_lv<7> > tmp_325_fu_279_p2;
    sc_signal< sc_lv<125> > tmp_322_fu_261_p4;
    sc_signal< sc_lv<7> > tmp_324_fu_274_p2;
    sc_signal< sc_lv<7> > tmp_326_fu_283_p3;
    sc_signal< sc_lv<7> > tmp_328_fu_298_p3;
    sc_signal< sc_lv<7> > tmp_329_fu_305_p2;
    sc_signal< sc_lv<125> > tmp_327_fu_291_p3;
    sc_signal< sc_lv<125> > tmp_330_fu_311_p1;
    sc_signal< sc_lv<125> > tmp_331_fu_315_p1;
    sc_signal< sc_lv<125> > tmp_332_fu_319_p2;
    sc_signal< sc_lv<125> > tmp_333_fu_325_p2;
    sc_signal< sc_lv<125> > p_Result_15_fu_331_p2;
    sc_signal< sc_lv<53> > grp_fu_341_p0;
    sc_signal< sc_lv<1> > ap_CS_fsm_state4;
    sc_signal< sc_lv<4> > tmp_177_fu_362_p2;
    sc_signal< sc_lv<53> > r_V_fu_379_p4;
    sc_signal< sc_lv<70> > r_V_7_fu_389_p1;
    sc_signal< sc_lv<7> > Li_fu_417_p4;
    sc_signal< sc_lv<17> > tmp_337_fu_433_p1;
    sc_signal< sc_lv<7> > Ui_1_fu_427_p2;
    sc_signal< sc_lv<8> > tmp_339_fu_447_p1;
    sc_signal< sc_lv<1> > tmp_338_fu_441_p2;
    sc_signal< sc_lv<8> > tmp_340_fu_451_p1;
    sc_signal< sc_lv<8> > tmp_341_fu_455_p2;
    sc_signal< sc_lv<8> > tmp_342_fu_461_p3;
    sc_signal< sc_lv<8> > tmp_344_fu_477_p3;
    sc_signal< sc_lv<8> > tmp_343_fu_469_p3;
    sc_signal< sc_lv<8> > tmp_345_fu_485_p2;
    sc_signal< sc_lv<178> > loc_V_fu_437_p1;
    sc_signal< sc_lv<178> > tmp_346_fu_491_p1;
    sc_signal< sc_lv<178> > tmp_349_fu_503_p2;
    sc_signal< sc_lv<178> > tmp_350_fu_509_p4;
    sc_signal< sc_lv<178> > tmp_347_fu_495_p1;
    sc_signal< sc_lv<178> > tmp_348_fu_499_p1;
    sc_signal< sc_lv<178> > tmp_352_fu_527_p2;
    sc_signal< sc_lv<178> > tmp_353_fu_533_p2;
    sc_signal< sc_lv<178> > p_demorgan_fu_539_p2;
    sc_signal< sc_lv<178> > tmp_354_fu_545_p2;
    sc_signal< sc_lv<178> > tmp_351_fu_519_p3;
    sc_signal< sc_lv<178> > tmp_355_fu_551_p2;
    sc_signal< sc_lv<178> > tmp_356_fu_557_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state24;
    sc_signal< sc_lv<59> > tmp_336_fu_569_p1;
    sc_signal< sc_lv<178> > p_Result_s_fu_573_p5;
    sc_signal< sc_lv<178> > ap_return_preg;
    sc_signal< sc_lv<24> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<24> ap_ST_fsm_state1;
    static const sc_lv<24> ap_ST_fsm_state2;
    static const sc_lv<24> ap_ST_fsm_state3;
    static const sc_lv<24> ap_ST_fsm_state4;
    static const sc_lv<24> ap_ST_fsm_state5;
    static const sc_lv<24> ap_ST_fsm_state6;
    static const sc_lv<24> ap_ST_fsm_state7;
    static const sc_lv<24> ap_ST_fsm_state8;
    static const sc_lv<24> ap_ST_fsm_state9;
    static const sc_lv<24> ap_ST_fsm_state10;
    static const sc_lv<24> ap_ST_fsm_state11;
    static const sc_lv<24> ap_ST_fsm_state12;
    static const sc_lv<24> ap_ST_fsm_state13;
    static const sc_lv<24> ap_ST_fsm_state14;
    static const sc_lv<24> ap_ST_fsm_state15;
    static const sc_lv<24> ap_ST_fsm_state16;
    static const sc_lv<24> ap_ST_fsm_state17;
    static const sc_lv<24> ap_ST_fsm_state18;
    static const sc_lv<24> ap_ST_fsm_state19;
    static const sc_lv<24> ap_ST_fsm_state20;
    static const sc_lv<24> ap_ST_fsm_state21;
    static const sc_lv<24> ap_ST_fsm_state22;
    static const sc_lv<24> ap_ST_fsm_state23;
    static const sc_lv<24> ap_ST_fsm_state24;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<7> ap_const_lv7_10;
    static const sc_lv<7> ap_const_lv7_7C;
    static const sc_lv<32> ap_const_lv32_7C;
    static const sc_lv<125> ap_const_lv125_1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<32> ap_const_lv32_45;
    static const sc_lv<3> ap_const_lv3_7;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<7> ap_const_lv7_6F;
    static const sc_lv<8> ap_const_lv8_B1;
    static const sc_lv<32> ap_const_lv32_B1;
    static const sc_lv<178> ap_const_lv178_lc_1;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_77;
    static const sc_lv<178> ap_const_lv178_lc_2;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_Li_fu_417_p4();
    void thread_Lo_assign_fu_235_p3();
    void thread_Ui_1_fu_427_p2();
    void thread_Ui_fu_249_p3();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_exitcond1_fu_213_p2();
    void thread_exitcond2_fu_351_p2();
    void thread_exitcond_fu_400_p2();
    void thread_grp_fu_341_p0();
    void thread_i_10_fu_373_p2();
    void thread_i_9_fu_219_p2();
    void thread_loc_V_fu_437_p1();
    void thread_p_Result_14_fu_563_p2();
    void thread_p_Result_15_fu_331_p2();
    void thread_p_Result_s_fu_573_p5();
    void thread_p_demorgan_fu_539_p2();
    void thread_pp_V_address0();
    void thread_pp_V_ce0();
    void thread_pp_V_we0();
    void thread_pps_V_address0();
    void thread_pps_V_ce0();
    void thread_pps_V_d0();
    void thread_pps_V_we0();
    void thread_r_V_7_fu_389_p1();
    void thread_r_V_fu_379_p4();
    void thread_tmp_172_fu_243_p2();
    void thread_tmp_173_fu_346_p1();
    void thread_tmp_176_fu_357_p1();
    void thread_tmp_177_fu_362_p2();
    void thread_tmp_178_fu_368_p1();
    void thread_tmp_179_fu_393_p2();
    void thread_tmp_180_fu_412_p1();
    void thread_tmp_181_fu_406_p2();
    void thread_tmp_320_fu_231_p1();
    void thread_tmp_321_fu_257_p2();
    void thread_tmp_322_fu_261_p4();
    void thread_tmp_323_fu_270_p2();
    void thread_tmp_324_fu_274_p2();
    void thread_tmp_325_fu_279_p2();
    void thread_tmp_326_fu_283_p3();
    void thread_tmp_327_fu_291_p3();
    void thread_tmp_328_fu_298_p3();
    void thread_tmp_329_fu_305_p2();
    void thread_tmp_330_fu_311_p1();
    void thread_tmp_331_fu_315_p1();
    void thread_tmp_332_fu_319_p2();
    void thread_tmp_333_fu_325_p2();
    void thread_tmp_335_fu_337_p1();
    void thread_tmp_336_fu_569_p1();
    void thread_tmp_337_fu_433_p1();
    void thread_tmp_338_fu_441_p2();
    void thread_tmp_339_fu_447_p1();
    void thread_tmp_340_fu_451_p1();
    void thread_tmp_341_fu_455_p2();
    void thread_tmp_342_fu_461_p3();
    void thread_tmp_343_fu_469_p3();
    void thread_tmp_344_fu_477_p3();
    void thread_tmp_345_fu_485_p2();
    void thread_tmp_346_fu_491_p1();
    void thread_tmp_347_fu_495_p1();
    void thread_tmp_348_fu_499_p1();
    void thread_tmp_349_fu_503_p2();
    void thread_tmp_350_fu_509_p4();
    void thread_tmp_351_fu_519_p3();
    void thread_tmp_352_fu_527_p2();
    void thread_tmp_353_fu_533_p2();
    void thread_tmp_354_fu_545_p2();
    void thread_tmp_355_fu_551_p2();
    void thread_tmp_356_fu_557_p2();
    void thread_tmp_fu_209_p1();
    void thread_tmp_s_fu_225_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
