// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _pulse_source_HH_
#define _pulse_source_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "sin_cos_range_redux_s.h"
#include "s_compute_acoustijbC.h"
#include "s_compute_acoustikbM.h"
#include "s_compute_acoustilbW.h"
#include "s_compute_acoustimb6.h"
#include "s_compute_acoustincg.h"

namespace ap_rtl {

struct pulse_source : public sc_module {
    // Port declarations 17
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > radius;
    sc_in< sc_lv<32> > step;
    sc_in< sc_lv<64> > amp;
    sc_out< sc_lv<14> > uc_address0;
    sc_out< sc_logic > uc_ce0;
    sc_out< sc_logic > uc_we0;
    sc_out< sc_lv<64> > uc_d0;
    sc_in< sc_lv<32> > ny;
    sc_in< sc_lv<32> > nx;
    sc_in< sc_lv<32> > scenario_source_x;
    sc_in< sc_lv<32> > scenario_source_y;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const2;
    sc_signal< sc_lv<5> > ap_var_for_const1;


    // Module declarations
    pulse_source(sc_module_name name);
    SC_HAS_PROCESS(pulse_source);

    ~pulse_source();

    sc_trace_file* mVcdFile;

    sin_cos_range_redux_s* grp_sin_cos_range_redux_s_fu_119;
    s_compute_acoustijbC<1,5,64,64,64>* s_compute_acoustijbC_U12;
    s_compute_acoustikbM<1,6,64,64,64>* s_compute_acoustikbM_U13;
    s_compute_acoustikbM<1,6,64,64,64>* s_compute_acoustikbM_U14;
    s_compute_acoustilbW<1,1,64,64,1>* s_compute_acoustilbW_U15;
    s_compute_acoustimb6<1,6,32,64>* s_compute_acoustimb6_U16;
    s_compute_acoustimb6<1,6,32,64>* s_compute_acoustimb6_U17;
    s_compute_acoustincg<1,31,64,64,64>* s_compute_acoustincg_U18;
    sc_signal< sc_lv<76> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<64> > grp_fu_146_p1;
    sc_signal< sc_lv<64> > reg_159;
    sc_signal< sc_lv<1> > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > ap_CS_fsm_state17;
    sc_signal< sc_lv<64> > grp_fu_132_p2;
    sc_signal< sc_lv<64> > reg_165;
    sc_signal< sc_lv<1> > ap_CS_fsm_state12;
    sc_signal< sc_lv<1> > ap_CS_fsm_state18;
    sc_signal< sc_lv<64> > tmp_193_i_to_int_fu_171_p1;
    sc_signal< sc_lv<64> > tmp_193_i_to_int_reg_363;
    sc_signal< sc_lv<1> > notrhs2_fu_179_p2;
    sc_signal< sc_lv<1> > notrhs2_reg_368;
    sc_signal< sc_lv<15> > tmp_316_fu_185_p1;
    sc_signal< sc_lv<15> > tmp_316_reg_373;
    sc_signal< sc_lv<1> > ap_CS_fsm_state19;
    sc_signal< sc_lv<64> > next_mul_fu_189_p2;
    sc_signal< sc_lv<64> > next_mul_reg_378;
    sc_signal< sc_lv<32> > i_fu_205_p2;
    sc_signal< sc_lv<32> > i_reg_386;
    sc_signal< sc_lv<32> > j_fu_221_p2;
    sc_signal< sc_lv<32> > j_reg_394;
    sc_signal< sc_lv<1> > ap_CS_fsm_state20;
    sc_signal< sc_lv<32> > tmp_i_fu_231_p2;
    sc_signal< sc_lv<1> > tmp_129_fu_215_p2;
    sc_signal< sc_lv<1> > notlhs1_fu_258_p2;
    sc_signal< sc_lv<1> > notlhs1_reg_409;
    sc_signal< sc_lv<64> > tmp_186_i_reg_414;
    sc_signal< sc_lv<1> > ap_CS_fsm_state25;
    sc_signal< sc_lv<64> > grp_fu_151_p1;
    sc_signal< sc_lv<64> > tmp_189_i_reg_420;
    sc_signal< sc_lv<64> > tmp_187_i_reg_426;
    sc_signal< sc_lv<1> > ap_CS_fsm_state31;
    sc_signal< sc_lv<64> > grp_fu_138_p2;
    sc_signal< sc_lv<64> > tmp_190_i_reg_431;
    sc_signal< sc_lv<64> > grp_fu_128_p2;
    sc_signal< sc_lv<64> > tmp_191_i_reg_436;
    sc_signal< sc_lv<1> > ap_CS_fsm_state36;
    sc_signal< sc_lv<64> > grp_fu_154_p2;
    sc_signal< sc_lv<64> > tmp_192_i_reg_441;
    sc_signal< sc_lv<1> > ap_CS_fsm_state67;
    sc_signal< sc_lv<1> > tmp_182_fu_309_p2;
    sc_signal< sc_lv<1> > tmp_182_reg_447;
    sc_signal< sc_lv<1> > ap_CS_fsm_state68;
    sc_signal< sc_lv<15> > tmp_252_fu_319_p2;
    sc_signal< sc_lv<15> > tmp_252_reg_451;
    sc_signal< sc_lv<63> > tmp_318_fu_328_p1;
    sc_signal< sc_lv<63> > tmp_318_reg_456;
    sc_signal< sc_lv<1> > ap_CS_fsm_state69;
    sc_signal< sc_logic > grp_sin_cos_range_redux_s_fu_119_ap_done;
    sc_signal< sc_lv<64> > ret_i_i_i_i_i_fu_339_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state70;
    sc_signal< sc_lv<64> > tmp_130_reg_466;
    sc_signal< sc_lv<1> > ap_CS_fsm_state75;
    sc_signal< sc_logic > grp_sin_cos_range_redux_s_fu_119_ap_start;
    sc_signal< sc_logic > grp_sin_cos_range_redux_s_fu_119_ap_idle;
    sc_signal< sc_logic > grp_sin_cos_range_redux_s_fu_119_ap_ready;
    sc_signal< sc_lv<64> > grp_sin_cos_range_redux_s_fu_119_ap_return;
    sc_signal< sc_lv<32> > x_assign_reg_84;
    sc_signal< sc_lv<64> > phi_mul_reg_96;
    sc_signal< sc_lv<32> > y_assign_reg_107;
    sc_signal< sc_lv<1> > ap_CS_fsm_state76;
    sc_signal< sc_lv<1> > tmp_127_fu_199_p2;
    sc_signal< sc_logic > ap_reg_grp_sin_cos_range_redux_s_fu_119_ap_start;
    sc_signal< sc_lv<64> > tmp_253_cast_fu_344_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state32;
    sc_signal< sc_lv<64> > grp_fu_132_p0;
    sc_signal< sc_lv<64> > grp_fu_132_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > ap_CS_fsm_state13;
    sc_signal< sc_lv<1> > ap_CS_fsm_state26;
    sc_signal< sc_lv<32> > grp_fu_146_p0;
    sc_signal< sc_lv<32> > grp_fu_151_p0;
    sc_signal< sc_lv<1> > ap_CS_fsm_state37;
    sc_signal< sc_lv<52> > tmp_315_fu_175_p1;
    sc_signal< sc_lv<11> > tmp_177_fu_249_p4;
    sc_signal< sc_lv<64> > tmp_192_i_to_int_fu_264_p1;
    sc_signal< sc_lv<11> > tmp_175_fu_267_p4;
    sc_signal< sc_lv<52> > tmp_317_fu_277_p1;
    sc_signal< sc_lv<1> > notrhs_fu_287_p2;
    sc_signal< sc_lv<1> > notlhs_fu_281_p2;
    sc_signal< sc_lv<1> > tmp_178_fu_293_p2;
    sc_signal< sc_lv<1> > tmp_179_fu_299_p2;
    sc_signal< sc_lv<1> > tmp_180_fu_303_p2;
    sc_signal< sc_lv<1> > tmp_181_fu_142_p2;
    sc_signal< sc_lv<15> > tmp_319_fu_315_p1;
    sc_signal< sc_lv<64> > p_Val2_s_fu_324_p1;
    sc_signal< sc_lv<64> > p_Result_s_fu_332_p3;
    sc_signal< sc_lv<76> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<76> ap_ST_fsm_state1;
    static const sc_lv<76> ap_ST_fsm_state2;
    static const sc_lv<76> ap_ST_fsm_state3;
    static const sc_lv<76> ap_ST_fsm_state4;
    static const sc_lv<76> ap_ST_fsm_state5;
    static const sc_lv<76> ap_ST_fsm_state6;
    static const sc_lv<76> ap_ST_fsm_state7;
    static const sc_lv<76> ap_ST_fsm_state8;
    static const sc_lv<76> ap_ST_fsm_state9;
    static const sc_lv<76> ap_ST_fsm_state10;
    static const sc_lv<76> ap_ST_fsm_state11;
    static const sc_lv<76> ap_ST_fsm_state12;
    static const sc_lv<76> ap_ST_fsm_state13;
    static const sc_lv<76> ap_ST_fsm_state14;
    static const sc_lv<76> ap_ST_fsm_state15;
    static const sc_lv<76> ap_ST_fsm_state16;
    static const sc_lv<76> ap_ST_fsm_state17;
    static const sc_lv<76> ap_ST_fsm_state18;
    static const sc_lv<76> ap_ST_fsm_state19;
    static const sc_lv<76> ap_ST_fsm_state20;
    static const sc_lv<76> ap_ST_fsm_state21;
    static const sc_lv<76> ap_ST_fsm_state22;
    static const sc_lv<76> ap_ST_fsm_state23;
    static const sc_lv<76> ap_ST_fsm_state24;
    static const sc_lv<76> ap_ST_fsm_state25;
    static const sc_lv<76> ap_ST_fsm_state26;
    static const sc_lv<76> ap_ST_fsm_state27;
    static const sc_lv<76> ap_ST_fsm_state28;
    static const sc_lv<76> ap_ST_fsm_state29;
    static const sc_lv<76> ap_ST_fsm_state30;
    static const sc_lv<76> ap_ST_fsm_state31;
    static const sc_lv<76> ap_ST_fsm_state32;
    static const sc_lv<76> ap_ST_fsm_state33;
    static const sc_lv<76> ap_ST_fsm_state34;
    static const sc_lv<76> ap_ST_fsm_state35;
    static const sc_lv<76> ap_ST_fsm_state36;
    static const sc_lv<76> ap_ST_fsm_state37;
    static const sc_lv<76> ap_ST_fsm_state38;
    static const sc_lv<76> ap_ST_fsm_state39;
    static const sc_lv<76> ap_ST_fsm_state40;
    static const sc_lv<76> ap_ST_fsm_state41;
    static const sc_lv<76> ap_ST_fsm_state42;
    static const sc_lv<76> ap_ST_fsm_state43;
    static const sc_lv<76> ap_ST_fsm_state44;
    static const sc_lv<76> ap_ST_fsm_state45;
    static const sc_lv<76> ap_ST_fsm_state46;
    static const sc_lv<76> ap_ST_fsm_state47;
    static const sc_lv<76> ap_ST_fsm_state48;
    static const sc_lv<76> ap_ST_fsm_state49;
    static const sc_lv<76> ap_ST_fsm_state50;
    static const sc_lv<76> ap_ST_fsm_state51;
    static const sc_lv<76> ap_ST_fsm_state52;
    static const sc_lv<76> ap_ST_fsm_state53;
    static const sc_lv<76> ap_ST_fsm_state54;
    static const sc_lv<76> ap_ST_fsm_state55;
    static const sc_lv<76> ap_ST_fsm_state56;
    static const sc_lv<76> ap_ST_fsm_state57;
    static const sc_lv<76> ap_ST_fsm_state58;
    static const sc_lv<76> ap_ST_fsm_state59;
    static const sc_lv<76> ap_ST_fsm_state60;
    static const sc_lv<76> ap_ST_fsm_state61;
    static const sc_lv<76> ap_ST_fsm_state62;
    static const sc_lv<76> ap_ST_fsm_state63;
    static const sc_lv<76> ap_ST_fsm_state64;
    static const sc_lv<76> ap_ST_fsm_state65;
    static const sc_lv<76> ap_ST_fsm_state66;
    static const sc_lv<76> ap_ST_fsm_state67;
    static const sc_lv<76> ap_ST_fsm_state68;
    static const sc_lv<76> ap_ST_fsm_state69;
    static const sc_lv<76> ap_ST_fsm_state70;
    static const sc_lv<76> ap_ST_fsm_state71;
    static const sc_lv<76> ap_ST_fsm_state72;
    static const sc_lv<76> ap_ST_fsm_state73;
    static const sc_lv<76> ap_ST_fsm_state74;
    static const sc_lv<76> ap_ST_fsm_state75;
    static const sc_lv<76> ap_ST_fsm_state76;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_23;
    static const sc_lv<32> ap_const_lv32_42;
    static const sc_lv<32> ap_const_lv32_43;
    static const sc_lv<32> ap_const_lv32_44;
    static const sc_lv<32> ap_const_lv32_45;
    static const sc_lv<32> ap_const_lv32_4A;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_4B;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<64> ap_const_lv64_400921FB54442D18;
    static const sc_lv<64> ap_const_lv64_3FD0000000000000;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<52> ap_const_lv52_0;
    static const sc_lv<64> ap_const_lv64_64;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<11> ap_const_lv11_7FF;
    static const sc_lv<5> ap_const_lv5_5;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state31();
    void thread_ap_CS_fsm_state32();
    void thread_ap_CS_fsm_state36();
    void thread_ap_CS_fsm_state37();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state67();
    void thread_ap_CS_fsm_state68();
    void thread_ap_CS_fsm_state69();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state70();
    void thread_ap_CS_fsm_state75();
    void thread_ap_CS_fsm_state76();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_fu_132_p0();
    void thread_grp_fu_132_p1();
    void thread_grp_fu_146_p0();
    void thread_grp_fu_151_p0();
    void thread_grp_sin_cos_range_redux_s_fu_119_ap_start();
    void thread_i_fu_205_p2();
    void thread_j_fu_221_p2();
    void thread_next_mul_fu_189_p2();
    void thread_notlhs1_fu_258_p2();
    void thread_notlhs_fu_281_p2();
    void thread_notrhs2_fu_179_p2();
    void thread_notrhs_fu_287_p2();
    void thread_p_Result_s_fu_332_p3();
    void thread_p_Val2_s_fu_324_p1();
    void thread_ret_i_i_i_i_i_fu_339_p1();
    void thread_tmp_127_fu_199_p2();
    void thread_tmp_129_fu_215_p2();
    void thread_tmp_175_fu_267_p4();
    void thread_tmp_177_fu_249_p4();
    void thread_tmp_178_fu_293_p2();
    void thread_tmp_179_fu_299_p2();
    void thread_tmp_180_fu_303_p2();
    void thread_tmp_182_fu_309_p2();
    void thread_tmp_192_i_to_int_fu_264_p1();
    void thread_tmp_193_i_to_int_fu_171_p1();
    void thread_tmp_252_fu_319_p2();
    void thread_tmp_253_cast_fu_344_p1();
    void thread_tmp_315_fu_175_p1();
    void thread_tmp_316_fu_185_p1();
    void thread_tmp_317_fu_277_p1();
    void thread_tmp_318_fu_328_p1();
    void thread_tmp_319_fu_315_p1();
    void thread_tmp_i_fu_231_p2();
    void thread_uc_address0();
    void thread_uc_ce0();
    void thread_uc_d0();
    void thread_uc_we0();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
